# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rules/profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rules/profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from rules import rule_config_pb2 as rules_dot_rule__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13rules/profile.proto\x12\x07profile\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17rules/rule_config.proto\"G\n\x07Profile\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12 \n\x05rules\x18\x03 \x03(\x0b\x32\x11.rules.RuleConfig2T\n\x0eProfileService\x12\x42\n\x14ProcessProfileStream\x12\x10.profile.Profile\x1a\x16.google.protobuf.Empty(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rules.profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILE']._serialized_start=86
  _globals['_PROFILE']._serialized_end=157
  _globals['_PROFILESERVICE']._serialized_start=159
  _globals['_PROFILESERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
