// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transaction.proto
// Protobuf C++ Version: 6.32.1

#include "transaction.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace transaction {

inline constexpr Transaction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        transaction_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sender_account_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        receiver_account_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        merchant_category_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        location_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ip_address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        amount_{0},
        transaction_type_{static_cast< ::transaction::Transaction_TransactionType >(0)},
        device_used_{static_cast< ::transaction::Transaction_DeviceUsed >(0)},
        payment_channel_{static_cast< ::transaction::Transaction_PaymentChannel >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Transaction::Transaction(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Transaction_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TransactionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransactionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransactionDefaultTypeInternal() {}
  union {
    Transaction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransactionDefaultTypeInternal _Transaction_default_instance_;
}  // namespace transaction
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_transaction_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_transaction_2eproto = nullptr;
const ::uint32_t
    TableStruct_transaction_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_._has_bits_),
        15, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.transaction_id_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.sender_account_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.receiver_account_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.amount_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.transaction_type_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.merchant_category_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.location_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.device_used_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.payment_channel_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.ip_address_),
        PROTOBUF_FIELD_OFFSET(::transaction::Transaction, _impl_.device_hash_),
        0,
        1,
        2,
        3,
        8,
        9,
        4,
        5,
        10,
        11,
        6,
        7,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::transaction::Transaction)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::transaction::_Transaction_default_instance_._instance,
};
const char descriptor_table_protodef_transaction_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021transaction.proto\022\013transaction\"\321\004\n\013Tra"
    "nsaction\022\026\n\016transaction_id\030\001 \001(\t\022\026\n\016send"
    "er_account\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t\022\030\n\020r"
    "eceiver_account\030\004 \001(\t\022\016\n\006amount\030\005 \001(\002\022B\n"
    "\020transaction_type\030\006 \001(\0162(.transaction.Tr"
    "ansaction.TransactionType\022\031\n\021merchant_ca"
    "tegory\030\007 \001(\t\022\020\n\010location\030\010 \001(\t\0228\n\013device"
    "_used\030\t \001(\0162#.transaction.Transaction.De"
    "viceUsed\022@\n\017payment_channel\030\n \001(\0162\'.tran"
    "saction.Transaction.PaymentChannel\022\022\n\nip"
    "_address\030\013 \001(\t\022\023\n\013device_hash\030\014 \001(\t\"I\n\017T"
    "ransactionType\022\016\n\nWITHDRAWAL\020\000\022\013\n\007DEPOSI"
    "T\020\001\022\014\n\010TRANSFER\020\002\022\013\n\007PAYMENT\020\003\"3\n\nDevice"
    "Used\022\n\n\006MOBILE\020\000\022\007\n\003ATM\020\001\022\007\n\003POS\020\002\022\007\n\003WE"
    "B\020\003\"\?\n\016PaymentChannel\022\007\n\003UPI\020\000\022\010\n\004CARD\020\001"
    "\022\007\n\003ACH\020\002\022\021\n\rWIRE_TRANSFER\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_transaction_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_transaction_2eproto = {
    false,
    false,
    636,
    descriptor_table_protodef_transaction_2eproto,
    "transaction.proto",
    &descriptor_table_transaction_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_transaction_2eproto::offsets,
    file_level_enum_descriptors_transaction_2eproto,
    file_level_service_descriptors_transaction_2eproto,
};
namespace transaction {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Transaction_TransactionType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_transaction_2eproto);
  return file_level_enum_descriptors_transaction_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Transaction_TransactionType_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Transaction_DeviceUsed_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_transaction_2eproto);
  return file_level_enum_descriptors_transaction_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Transaction_DeviceUsed_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Transaction_PaymentChannel_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_transaction_2eproto);
  return file_level_enum_descriptors_transaction_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t Transaction_PaymentChannel_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class Transaction::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Transaction>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Transaction, _impl_._has_bits_);
};

Transaction::Transaction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Transaction_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:transaction.Transaction)
}
PROTOBUF_NDEBUG_INLINE Transaction::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::transaction::Transaction& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        transaction_id_(arena, from.transaction_id_),
        sender_account_(arena, from.sender_account_),
        timestamp_(arena, from.timestamp_),
        receiver_account_(arena, from.receiver_account_),
        merchant_category_(arena, from.merchant_category_),
        location_(arena, from.location_),
        ip_address_(arena, from.ip_address_),
        device_hash_(arena, from.device_hash_) {}

Transaction::Transaction(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Transaction& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Transaction_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Transaction* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, amount_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, amount_),
           offsetof(Impl_, payment_channel_) -
               offsetof(Impl_, amount_) +
               sizeof(Impl_::payment_channel_));

  // @@protoc_insertion_point(copy_constructor:transaction.Transaction)
}
PROTOBUF_NDEBUG_INLINE Transaction::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        transaction_id_(arena),
        sender_account_(arena),
        timestamp_(arena),
        receiver_account_(arena),
        merchant_category_(arena),
        location_(arena),
        ip_address_(arena),
        device_hash_(arena) {}

inline void Transaction::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, amount_),
           0,
           offsetof(Impl_, payment_channel_) -
               offsetof(Impl_, amount_) +
               sizeof(Impl_::payment_channel_));
}
Transaction::~Transaction() {
  // @@protoc_insertion_point(destructor:transaction.Transaction)
  SharedDtor(*this);
}
inline void Transaction::SharedDtor(MessageLite& self) {
  Transaction& this_ = static_cast<Transaction&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.transaction_id_.Destroy();
  this_._impl_.sender_account_.Destroy();
  this_._impl_.timestamp_.Destroy();
  this_._impl_.receiver_account_.Destroy();
  this_._impl_.merchant_category_.Destroy();
  this_._impl_.location_.Destroy();
  this_._impl_.ip_address_.Destroy();
  this_._impl_.device_hash_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Transaction::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Transaction(arena);
}
constexpr auto Transaction::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Transaction),
                                            alignof(Transaction));
}
constexpr auto Transaction::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Transaction_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Transaction::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Transaction>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Transaction::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Transaction>(), &Transaction::ByteSizeLong,
              &Transaction::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Transaction, _impl_._cached_size_),
          false,
      },
      &Transaction::kDescriptorMethods,
      &descriptor_table_transaction_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Transaction_class_data_ =
        Transaction::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Transaction::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Transaction_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Transaction_class_data_.tc_table);
  return Transaction_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 12, 0, 139, 2>
Transaction::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Transaction, _impl_._has_bits_),
    0, // no _extensions_
    12, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294963200,  // skipmap
    offsetof(decltype(_table_), field_entries),
    12,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Transaction_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::transaction::Transaction>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string transaction_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.transaction_id_)}},
    // string sender_account = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.sender_account_)}},
    // string timestamp = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.timestamp_)}},
    // string receiver_account = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 3, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.receiver_account_)}},
    // float amount = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 8, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.amount_)}},
    // .transaction.Transaction.TransactionType transaction_type = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Transaction, _impl_.transaction_type_), 9>(),
     {48, 9, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.transaction_type_)}},
    // string merchant_category = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 4, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.merchant_category_)}},
    // string location = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 5, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.location_)}},
    // .transaction.Transaction.DeviceUsed device_used = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Transaction, _impl_.device_used_), 10>(),
     {72, 10, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.device_used_)}},
    // .transaction.Transaction.PaymentChannel payment_channel = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Transaction, _impl_.payment_channel_), 11>(),
     {80, 11, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.payment_channel_)}},
    // string ip_address = 11;
    {::_pbi::TcParser::FastUS1,
     {90, 6, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.ip_address_)}},
    // string device_hash = 12;
    {::_pbi::TcParser::FastUS1,
     {98, 7, 0, PROTOBUF_FIELD_OFFSET(Transaction, _impl_.device_hash_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string transaction_id = 1;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.transaction_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string sender_account = 2;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.sender_account_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string receiver_account = 4;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.receiver_account_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float amount = 5;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.amount_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // .transaction.Transaction.TransactionType transaction_type = 6;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.transaction_type_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string merchant_category = 7;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.merchant_category_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string location = 8;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.location_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .transaction.Transaction.DeviceUsed device_used = 9;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.device_used_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .transaction.Transaction.PaymentChannel payment_channel = 10;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.payment_channel_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string ip_address = 11;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.ip_address_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string device_hash = 12;
    {PROTOBUF_FIELD_OFFSET(Transaction, _impl_.device_hash_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\16\16\11\20\0\0\21\10\0\0\12\13\0\0\0"
    "transaction.Transaction"
    "transaction_id"
    "sender_account"
    "timestamp"
    "receiver_account"
    "merchant_category"
    "location"
    "ip_address"
    "device_hash"
  }},
};
PROTOBUF_NOINLINE void Transaction::Clear() {
// @@protoc_insertion_point(message_clear_start:transaction.Transaction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.transaction_id_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.sender_account_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _impl_.timestamp_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      _impl_.receiver_account_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000010U) != 0) {
      _impl_.merchant_category_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000020U) != 0) {
      _impl_.location_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000040U) != 0) {
      _impl_.ip_address_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000080U) != 0) {
      _impl_.device_hash_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x00000f00U) != 0) {
    ::memset(&_impl_.amount_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.payment_channel_) -
        reinterpret_cast<char*>(&_impl_.amount_)) + sizeof(_impl_.payment_channel_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Transaction::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Transaction& this_ = static_cast<const Transaction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Transaction::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Transaction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:transaction.Transaction)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string transaction_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_transaction_id().empty()) {
      const ::std::string& _s = this_._internal_transaction_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transaction.Transaction.transaction_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string sender_account = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (!this_._internal_sender_account().empty()) {
      const ::std::string& _s = this_._internal_sender_account();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transaction.Transaction.sender_account");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string timestamp = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (!this_._internal_timestamp().empty()) {
      const ::std::string& _s = this_._internal_timestamp();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transaction.Transaction.timestamp");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string receiver_account = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008U) != 0) {
    if (!this_._internal_receiver_account().empty()) {
      const ::std::string& _s = this_._internal_receiver_account();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transaction.Transaction.receiver_account");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // float amount = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000100U) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_amount()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          5, this_._internal_amount(), target);
    }
  }

  // .transaction.Transaction.TransactionType transaction_type = 6;
  if ((this_._impl_._has_bits_[0] & 0x00000200U) != 0) {
    if (this_._internal_transaction_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          6, this_._internal_transaction_type(), target);
    }
  }

  // string merchant_category = 7;
  if ((this_._impl_._has_bits_[0] & 0x00000010U) != 0) {
    if (!this_._internal_merchant_category().empty()) {
      const ::std::string& _s = this_._internal_merchant_category();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transaction.Transaction.merchant_category");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // string location = 8;
  if ((this_._impl_._has_bits_[0] & 0x00000020U) != 0) {
    if (!this_._internal_location().empty()) {
      const ::std::string& _s = this_._internal_location();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transaction.Transaction.location");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  // .transaction.Transaction.DeviceUsed device_used = 9;
  if ((this_._impl_._has_bits_[0] & 0x00000400U) != 0) {
    if (this_._internal_device_used() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          9, this_._internal_device_used(), target);
    }
  }

  // .transaction.Transaction.PaymentChannel payment_channel = 10;
  if ((this_._impl_._has_bits_[0] & 0x00000800U) != 0) {
    if (this_._internal_payment_channel() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          10, this_._internal_payment_channel(), target);
    }
  }

  // string ip_address = 11;
  if ((this_._impl_._has_bits_[0] & 0x00000040U) != 0) {
    if (!this_._internal_ip_address().empty()) {
      const ::std::string& _s = this_._internal_ip_address();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transaction.Transaction.ip_address");
      target = stream->WriteStringMaybeAliased(11, _s, target);
    }
  }

  // string device_hash = 12;
  if ((this_._impl_._has_bits_[0] & 0x00000080U) != 0) {
    if (!this_._internal_device_hash().empty()) {
      const ::std::string& _s = this_._internal_device_hash();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transaction.Transaction.device_hash");
      target = stream->WriteStringMaybeAliased(12, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:transaction.Transaction)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Transaction::ByteSizeLong(const MessageLite& base) {
  const Transaction& this_ = static_cast<const Transaction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Transaction::ByteSizeLong() const {
  const Transaction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:transaction.Transaction)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    // string transaction_id = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_transaction_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_transaction_id());
      }
    }
    // string sender_account = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!this_._internal_sender_account().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_sender_account());
      }
    }
    // string timestamp = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (!this_._internal_timestamp().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_timestamp());
      }
    }
    // string receiver_account = 4;
    if ((cached_has_bits & 0x00000008U) != 0) {
      if (!this_._internal_receiver_account().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_receiver_account());
      }
    }
    // string merchant_category = 7;
    if ((cached_has_bits & 0x00000010U) != 0) {
      if (!this_._internal_merchant_category().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_merchant_category());
      }
    }
    // string location = 8;
    if ((cached_has_bits & 0x00000020U) != 0) {
      if (!this_._internal_location().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_location());
      }
    }
    // string ip_address = 11;
    if ((cached_has_bits & 0x00000040U) != 0) {
      if (!this_._internal_ip_address().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ip_address());
      }
    }
    // string device_hash = 12;
    if ((cached_has_bits & 0x00000080U) != 0) {
      if (!this_._internal_device_hash().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_device_hash());
      }
    }
  }
  if ((cached_has_bits & 0x00000f00U) != 0) {
    // float amount = 5;
    if ((cached_has_bits & 0x00000100U) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_amount()) != 0) {
        total_size += 5;
      }
    }
    // .transaction.Transaction.TransactionType transaction_type = 6;
    if ((cached_has_bits & 0x00000200U) != 0) {
      if (this_._internal_transaction_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_transaction_type());
      }
    }
    // .transaction.Transaction.DeviceUsed device_used = 9;
    if ((cached_has_bits & 0x00000400U) != 0) {
      if (this_._internal_device_used() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_device_used());
      }
    }
    // .transaction.Transaction.PaymentChannel payment_channel = 10;
    if ((cached_has_bits & 0x00000800U) != 0) {
      if (this_._internal_payment_channel() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_payment_channel());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Transaction::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Transaction*>(&to_msg);
  auto& from = static_cast<const Transaction&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:transaction.Transaction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_transaction_id().empty()) {
        _this->_internal_set_transaction_id(from._internal_transaction_id());
      } else {
        if (_this->_impl_.transaction_id_.IsDefault()) {
          _this->_internal_set_transaction_id("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!from._internal_sender_account().empty()) {
        _this->_internal_set_sender_account(from._internal_sender_account());
      } else {
        if (_this->_impl_.sender_account_.IsDefault()) {
          _this->_internal_set_sender_account("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (!from._internal_timestamp().empty()) {
        _this->_internal_set_timestamp(from._internal_timestamp());
      } else {
        if (_this->_impl_.timestamp_.IsDefault()) {
          _this->_internal_set_timestamp("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      if (!from._internal_receiver_account().empty()) {
        _this->_internal_set_receiver_account(from._internal_receiver_account());
      } else {
        if (_this->_impl_.receiver_account_.IsDefault()) {
          _this->_internal_set_receiver_account("");
        }
      }
    }
    if ((cached_has_bits & 0x00000010U) != 0) {
      if (!from._internal_merchant_category().empty()) {
        _this->_internal_set_merchant_category(from._internal_merchant_category());
      } else {
        if (_this->_impl_.merchant_category_.IsDefault()) {
          _this->_internal_set_merchant_category("");
        }
      }
    }
    if ((cached_has_bits & 0x00000020U) != 0) {
      if (!from._internal_location().empty()) {
        _this->_internal_set_location(from._internal_location());
      } else {
        if (_this->_impl_.location_.IsDefault()) {
          _this->_internal_set_location("");
        }
      }
    }
    if ((cached_has_bits & 0x00000040U) != 0) {
      if (!from._internal_ip_address().empty()) {
        _this->_internal_set_ip_address(from._internal_ip_address());
      } else {
        if (_this->_impl_.ip_address_.IsDefault()) {
          _this->_internal_set_ip_address("");
        }
      }
    }
    if ((cached_has_bits & 0x00000080U) != 0) {
      if (!from._internal_device_hash().empty()) {
        _this->_internal_set_device_hash(from._internal_device_hash());
      } else {
        if (_this->_impl_.device_hash_.IsDefault()) {
          _this->_internal_set_device_hash("");
        }
      }
    }
  }
  if ((cached_has_bits & 0x00000f00U) != 0) {
    if ((cached_has_bits & 0x00000100U) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_amount()) != 0) {
        _this->_impl_.amount_ = from._impl_.amount_;
      }
    }
    if ((cached_has_bits & 0x00000200U) != 0) {
      if (from._internal_transaction_type() != 0) {
        _this->_impl_.transaction_type_ = from._impl_.transaction_type_;
      }
    }
    if ((cached_has_bits & 0x00000400U) != 0) {
      if (from._internal_device_used() != 0) {
        _this->_impl_.device_used_ = from._impl_.device_used_;
      }
    }
    if ((cached_has_bits & 0x00000800U) != 0) {
      if (from._internal_payment_channel() != 0) {
        _this->_impl_.payment_channel_ = from._impl_.payment_channel_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Transaction::CopyFrom(const Transaction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:transaction.Transaction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Transaction::InternalSwap(Transaction* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.transaction_id_, &other->_impl_.transaction_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_account_, &other->_impl_.sender_account_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.timestamp_, &other->_impl_.timestamp_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.receiver_account_, &other->_impl_.receiver_account_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.merchant_category_, &other->_impl_.merchant_category_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.location_, &other->_impl_.location_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_address_, &other->_impl_.ip_address_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_hash_, &other->_impl_.device_hash_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Transaction, _impl_.payment_channel_)
      + sizeof(Transaction::_impl_.payment_channel_)
      - PROTOBUF_FIELD_OFFSET(Transaction, _impl_.amount_)>(
          reinterpret_cast<char*>(&_impl_.amount_),
          reinterpret_cast<char*>(&other->_impl_.amount_));
}

::google::protobuf::Metadata Transaction::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace transaction
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_transaction_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
