// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transaction.proto
// Protobuf C++ Version: 6.32.1

#ifndef transaction_2eproto_2epb_2eh
#define transaction_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_transaction_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_transaction_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_transaction_2eproto;
}  // extern "C"
namespace transaction {
enum Transaction_DeviceUsed : int;
extern const uint32_t Transaction_DeviceUsed_internal_data_[];
enum Transaction_PaymentChannel : int;
extern const uint32_t Transaction_PaymentChannel_internal_data_[];
enum Transaction_TransactionType : int;
extern const uint32_t Transaction_TransactionType_internal_data_[];
class Transaction;
struct TransactionDefaultTypeInternal;
extern TransactionDefaultTypeInternal _Transaction_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Transaction_class_data_;
}  // namespace transaction
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::transaction::Transaction_DeviceUsed_internal_data_>
    internal::EnumTraitsImpl::value<::transaction::Transaction_DeviceUsed>;
template <>
internal::EnumTraitsT<::transaction::Transaction_PaymentChannel_internal_data_>
    internal::EnumTraitsImpl::value<::transaction::Transaction_PaymentChannel>;
template <>
internal::EnumTraitsT<::transaction::Transaction_TransactionType_internal_data_>
    internal::EnumTraitsImpl::value<::transaction::Transaction_TransactionType>;
}  // namespace protobuf
}  // namespace google

namespace transaction {
enum Transaction_TransactionType : int {
  Transaction_TransactionType_WITHDRAWAL = 0,
  Transaction_TransactionType_DEPOSIT = 1,
  Transaction_TransactionType_TRANSFER = 2,
  Transaction_TransactionType_PAYMENT = 3,
  Transaction_TransactionType_Transaction_TransactionType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Transaction_TransactionType_Transaction_TransactionType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Transaction_TransactionType_internal_data_[];
inline constexpr Transaction_TransactionType Transaction_TransactionType_TransactionType_MIN =
    static_cast<Transaction_TransactionType>(0);
inline constexpr Transaction_TransactionType Transaction_TransactionType_TransactionType_MAX =
    static_cast<Transaction_TransactionType>(3);
inline bool Transaction_TransactionType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int Transaction_TransactionType_TransactionType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Transaction_TransactionType_descriptor();
template <typename T>
const ::std::string& Transaction_TransactionType_Name(T value) {
  static_assert(::std::is_same<T, Transaction_TransactionType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TransactionType_Name().");
  return Transaction_TransactionType_Name(static_cast<Transaction_TransactionType>(value));
}
template <>
inline const ::std::string& Transaction_TransactionType_Name(Transaction_TransactionType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Transaction_TransactionType_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool Transaction_TransactionType_Parse(
    ::absl::string_view name, Transaction_TransactionType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Transaction_TransactionType>(Transaction_TransactionType_descriptor(), name,
                                           value);
}
enum Transaction_DeviceUsed : int {
  Transaction_DeviceUsed_MOBILE = 0,
  Transaction_DeviceUsed_ATM = 1,
  Transaction_DeviceUsed_POS = 2,
  Transaction_DeviceUsed_WEB = 3,
  Transaction_DeviceUsed_Transaction_DeviceUsed_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Transaction_DeviceUsed_Transaction_DeviceUsed_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Transaction_DeviceUsed_internal_data_[];
inline constexpr Transaction_DeviceUsed Transaction_DeviceUsed_DeviceUsed_MIN =
    static_cast<Transaction_DeviceUsed>(0);
inline constexpr Transaction_DeviceUsed Transaction_DeviceUsed_DeviceUsed_MAX =
    static_cast<Transaction_DeviceUsed>(3);
inline bool Transaction_DeviceUsed_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int Transaction_DeviceUsed_DeviceUsed_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Transaction_DeviceUsed_descriptor();
template <typename T>
const ::std::string& Transaction_DeviceUsed_Name(T value) {
  static_assert(::std::is_same<T, Transaction_DeviceUsed>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to DeviceUsed_Name().");
  return Transaction_DeviceUsed_Name(static_cast<Transaction_DeviceUsed>(value));
}
template <>
inline const ::std::string& Transaction_DeviceUsed_Name(Transaction_DeviceUsed value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Transaction_DeviceUsed_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool Transaction_DeviceUsed_Parse(
    ::absl::string_view name, Transaction_DeviceUsed* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Transaction_DeviceUsed>(Transaction_DeviceUsed_descriptor(), name,
                                           value);
}
enum Transaction_PaymentChannel : int {
  Transaction_PaymentChannel_UPI = 0,
  Transaction_PaymentChannel_CARD = 1,
  Transaction_PaymentChannel_ACH = 2,
  Transaction_PaymentChannel_WIRE_TRANSFER = 3,
  Transaction_PaymentChannel_Transaction_PaymentChannel_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Transaction_PaymentChannel_Transaction_PaymentChannel_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Transaction_PaymentChannel_internal_data_[];
inline constexpr Transaction_PaymentChannel Transaction_PaymentChannel_PaymentChannel_MIN =
    static_cast<Transaction_PaymentChannel>(0);
inline constexpr Transaction_PaymentChannel Transaction_PaymentChannel_PaymentChannel_MAX =
    static_cast<Transaction_PaymentChannel>(3);
inline bool Transaction_PaymentChannel_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int Transaction_PaymentChannel_PaymentChannel_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Transaction_PaymentChannel_descriptor();
template <typename T>
const ::std::string& Transaction_PaymentChannel_Name(T value) {
  static_assert(::std::is_same<T, Transaction_PaymentChannel>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PaymentChannel_Name().");
  return Transaction_PaymentChannel_Name(static_cast<Transaction_PaymentChannel>(value));
}
template <>
inline const ::std::string& Transaction_PaymentChannel_Name(Transaction_PaymentChannel value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Transaction_PaymentChannel_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool Transaction_PaymentChannel_Parse(
    ::absl::string_view name, Transaction_PaymentChannel* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Transaction_PaymentChannel>(Transaction_PaymentChannel_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Transaction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:transaction.Transaction) */ {
 public:
  inline Transaction() : Transaction(nullptr) {}
  ~Transaction() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Transaction* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Transaction));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Transaction(::google::protobuf::internal::ConstantInitialized);

  inline Transaction(const Transaction& from) : Transaction(nullptr, from) {}
  inline Transaction(Transaction&& from) noexcept
      : Transaction(nullptr, ::std::move(from)) {}
  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }
  inline Transaction& operator=(Transaction&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Transaction& default_instance() {
    return *reinterpret_cast<const Transaction*>(
        &_Transaction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Transaction& a, Transaction& b) { a.Swap(&b); }
  inline void Swap(Transaction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Transaction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Transaction* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Transaction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Transaction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Transaction& from) { Transaction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Transaction* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "transaction.Transaction"; }

 protected:
  explicit Transaction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Transaction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Transaction& from);
  Transaction(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Transaction&& from) noexcept
      : Transaction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using TransactionType = Transaction_TransactionType;
  static constexpr TransactionType WITHDRAWAL = Transaction_TransactionType_WITHDRAWAL;
  static constexpr TransactionType DEPOSIT = Transaction_TransactionType_DEPOSIT;
  static constexpr TransactionType TRANSFER = Transaction_TransactionType_TRANSFER;
  static constexpr TransactionType PAYMENT = Transaction_TransactionType_PAYMENT;
  static inline bool TransactionType_IsValid(int value) {
    return Transaction_TransactionType_IsValid(value);
  }
  static constexpr TransactionType TransactionType_MIN = Transaction_TransactionType_TransactionType_MIN;
  static constexpr TransactionType TransactionType_MAX = Transaction_TransactionType_TransactionType_MAX;
  static constexpr int TransactionType_ARRAYSIZE = Transaction_TransactionType_TransactionType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TransactionType_descriptor() {
    return Transaction_TransactionType_descriptor();
  }
  template <typename T>
  static inline const ::std::string& TransactionType_Name(T value) {
    return Transaction_TransactionType_Name(value);
  }
  static inline bool TransactionType_Parse(
      ::absl::string_view name, TransactionType* PROTOBUF_NONNULL value) {
    return Transaction_TransactionType_Parse(name, value);
  }
  using DeviceUsed = Transaction_DeviceUsed;
  static constexpr DeviceUsed MOBILE = Transaction_DeviceUsed_MOBILE;
  static constexpr DeviceUsed ATM = Transaction_DeviceUsed_ATM;
  static constexpr DeviceUsed POS = Transaction_DeviceUsed_POS;
  static constexpr DeviceUsed WEB = Transaction_DeviceUsed_WEB;
  static inline bool DeviceUsed_IsValid(int value) {
    return Transaction_DeviceUsed_IsValid(value);
  }
  static constexpr DeviceUsed DeviceUsed_MIN = Transaction_DeviceUsed_DeviceUsed_MIN;
  static constexpr DeviceUsed DeviceUsed_MAX = Transaction_DeviceUsed_DeviceUsed_MAX;
  static constexpr int DeviceUsed_ARRAYSIZE = Transaction_DeviceUsed_DeviceUsed_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DeviceUsed_descriptor() {
    return Transaction_DeviceUsed_descriptor();
  }
  template <typename T>
  static inline const ::std::string& DeviceUsed_Name(T value) {
    return Transaction_DeviceUsed_Name(value);
  }
  static inline bool DeviceUsed_Parse(
      ::absl::string_view name, DeviceUsed* PROTOBUF_NONNULL value) {
    return Transaction_DeviceUsed_Parse(name, value);
  }
  using PaymentChannel = Transaction_PaymentChannel;
  static constexpr PaymentChannel UPI = Transaction_PaymentChannel_UPI;
  static constexpr PaymentChannel CARD = Transaction_PaymentChannel_CARD;
  static constexpr PaymentChannel ACH = Transaction_PaymentChannel_ACH;
  static constexpr PaymentChannel WIRE_TRANSFER = Transaction_PaymentChannel_WIRE_TRANSFER;
  static inline bool PaymentChannel_IsValid(int value) {
    return Transaction_PaymentChannel_IsValid(value);
  }
  static constexpr PaymentChannel PaymentChannel_MIN = Transaction_PaymentChannel_PaymentChannel_MIN;
  static constexpr PaymentChannel PaymentChannel_MAX = Transaction_PaymentChannel_PaymentChannel_MAX;
  static constexpr int PaymentChannel_ARRAYSIZE = Transaction_PaymentChannel_PaymentChannel_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PaymentChannel_descriptor() {
    return Transaction_PaymentChannel_descriptor();
  }
  template <typename T>
  static inline const ::std::string& PaymentChannel_Name(T value) {
    return Transaction_PaymentChannel_Name(value);
  }
  static inline bool PaymentChannel_Parse(
      ::absl::string_view name, PaymentChannel* PROTOBUF_NONNULL value) {
    return Transaction_PaymentChannel_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kTransactionIdFieldNumber = 1,
    kSenderAccountFieldNumber = 2,
    kTimestampFieldNumber = 3,
    kReceiverAccountFieldNumber = 4,
    kMerchantCategoryFieldNumber = 7,
    kLocationFieldNumber = 8,
    kIpAddressFieldNumber = 11,
    kDeviceHashFieldNumber = 12,
    kAmountFieldNumber = 5,
    kTransactionTypeFieldNumber = 6,
    kDeviceUsedFieldNumber = 9,
    kPaymentChannelFieldNumber = 10,
  };
  // string transaction_id = 1;
  void clear_transaction_id() ;
  const ::std::string& transaction_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_transaction_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_transaction_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_transaction_id();
  void set_allocated_transaction_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_transaction_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_transaction_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_transaction_id();

  public:
  // string sender_account = 2;
  void clear_sender_account() ;
  const ::std::string& sender_account() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sender_account(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sender_account();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sender_account();
  void set_allocated_sender_account(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sender_account() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sender_account(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sender_account();

  public:
  // string timestamp = 3;
  void clear_timestamp() ;
  const ::std::string& timestamp() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_timestamp(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_timestamp();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_timestamp();
  void set_allocated_timestamp(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_timestamp() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_timestamp();

  public:
  // string receiver_account = 4;
  void clear_receiver_account() ;
  const ::std::string& receiver_account() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_receiver_account(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_receiver_account();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_receiver_account();
  void set_allocated_receiver_account(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_receiver_account() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_receiver_account(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_receiver_account();

  public:
  // string merchant_category = 7;
  void clear_merchant_category() ;
  const ::std::string& merchant_category() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_merchant_category(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_merchant_category();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_merchant_category();
  void set_allocated_merchant_category(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_merchant_category() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_merchant_category(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_merchant_category();

  public:
  // string location = 8;
  void clear_location() ;
  const ::std::string& location() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_location(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_location();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_location();
  void set_allocated_location(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_location() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_location(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_location();

  public:
  // string ip_address = 11;
  void clear_ip_address() ;
  const ::std::string& ip_address() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ip_address(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ip_address();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ip_address();
  void set_allocated_ip_address(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ip_address() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ip_address(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ip_address();

  public:
  // string device_hash = 12;
  void clear_device_hash() ;
  const ::std::string& device_hash() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_device_hash(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_device_hash();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_device_hash();
  void set_allocated_device_hash(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_device_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_device_hash(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_device_hash();

  public:
  // float amount = 5;
  void clear_amount() ;
  float amount() const;
  void set_amount(float value);

  private:
  float _internal_amount() const;
  void _internal_set_amount(float value);

  public:
  // .transaction.Transaction.TransactionType transaction_type = 6;
  void clear_transaction_type() ;
  ::transaction::Transaction_TransactionType transaction_type() const;
  void set_transaction_type(::transaction::Transaction_TransactionType value);

  private:
  ::transaction::Transaction_TransactionType _internal_transaction_type() const;
  void _internal_set_transaction_type(::transaction::Transaction_TransactionType value);

  public:
  // .transaction.Transaction.DeviceUsed device_used = 9;
  void clear_device_used() ;
  ::transaction::Transaction_DeviceUsed device_used() const;
  void set_device_used(::transaction::Transaction_DeviceUsed value);

  private:
  ::transaction::Transaction_DeviceUsed _internal_device_used() const;
  void _internal_set_device_used(::transaction::Transaction_DeviceUsed value);

  public:
  // .transaction.Transaction.PaymentChannel payment_channel = 10;
  void clear_payment_channel() ;
  ::transaction::Transaction_PaymentChannel payment_channel() const;
  void set_payment_channel(::transaction::Transaction_PaymentChannel value);

  private:
  ::transaction::Transaction_PaymentChannel _internal_payment_channel() const;
  void _internal_set_payment_channel(::transaction::Transaction_PaymentChannel value);

  public:
  // @@protoc_insertion_point(class_scope:transaction.Transaction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 12,
                                   0, 139,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Transaction& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr transaction_id_;
    ::google::protobuf::internal::ArenaStringPtr sender_account_;
    ::google::protobuf::internal::ArenaStringPtr timestamp_;
    ::google::protobuf::internal::ArenaStringPtr receiver_account_;
    ::google::protobuf::internal::ArenaStringPtr merchant_category_;
    ::google::protobuf::internal::ArenaStringPtr location_;
    ::google::protobuf::internal::ArenaStringPtr ip_address_;
    ::google::protobuf::internal::ArenaStringPtr device_hash_;
    float amount_;
    int transaction_type_;
    int device_used_;
    int payment_channel_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transaction_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Transaction_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Transaction

// string transaction_id = 1;
inline void Transaction::clear_transaction_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transaction_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& Transaction::transaction_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transaction.Transaction.transaction_id)
  return _internal_transaction_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_transaction_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.transaction_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:transaction.Transaction.transaction_id)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_transaction_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_transaction_id();
  // @@protoc_insertion_point(field_mutable:transaction.Transaction.transaction_id)
  return _s;
}
inline const ::std::string& Transaction::_internal_transaction_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.transaction_id_.Get();
}
inline void Transaction::_internal_set_transaction_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.transaction_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_transaction_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.transaction_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_transaction_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:transaction.Transaction.transaction_id)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.transaction_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.transaction_id_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_transaction_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.transaction_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.transaction_id_.IsDefault()) {
    _impl_.transaction_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:transaction.Transaction.transaction_id)
}

// string sender_account = 2;
inline void Transaction::clear_sender_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sender_account_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& Transaction::sender_account() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transaction.Transaction.sender_account)
  return _internal_sender_account();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_sender_account(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.sender_account_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:transaction.Transaction.sender_account)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_sender_account()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_sender_account();
  // @@protoc_insertion_point(field_mutable:transaction.Transaction.sender_account)
  return _s;
}
inline const ::std::string& Transaction::_internal_sender_account() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sender_account_.Get();
}
inline void Transaction::_internal_set_sender_account(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.sender_account_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_sender_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.sender_account_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_sender_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:transaction.Transaction.sender_account)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.sender_account_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sender_account_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_sender_account(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.sender_account_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sender_account_.IsDefault()) {
    _impl_.sender_account_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:transaction.Transaction.sender_account)
}

// string timestamp = 3;
inline void Transaction::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline const ::std::string& Transaction::timestamp() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transaction.Transaction.timestamp)
  return _internal_timestamp();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_timestamp(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.timestamp_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:transaction.Transaction.timestamp)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_timestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:transaction.Transaction.timestamp)
  return _s;
}
inline const ::std::string& Transaction::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_.Get();
}
inline void Transaction::_internal_set_timestamp(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.timestamp_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  return _impl_.timestamp_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:transaction.Transaction.timestamp)
  if ((_impl_._has_bits_[0] & 0x00000004U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004U;
  auto* released = _impl_.timestamp_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_timestamp(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  _impl_.timestamp_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:transaction.Transaction.timestamp)
}

// string receiver_account = 4;
inline void Transaction::clear_receiver_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.receiver_account_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline const ::std::string& Transaction::receiver_account() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transaction.Transaction.receiver_account)
  return _internal_receiver_account();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_receiver_account(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008U;
  _impl_.receiver_account_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:transaction.Transaction.receiver_account)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_receiver_account()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_receiver_account();
  // @@protoc_insertion_point(field_mutable:transaction.Transaction.receiver_account)
  return _s;
}
inline const ::std::string& Transaction::_internal_receiver_account() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.receiver_account_.Get();
}
inline void Transaction::_internal_set_receiver_account(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008U;
  _impl_.receiver_account_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_receiver_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008U;
  return _impl_.receiver_account_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_receiver_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:transaction.Transaction.receiver_account)
  if ((_impl_._has_bits_[0] & 0x00000008U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008U;
  auto* released = _impl_.receiver_account_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.receiver_account_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_receiver_account(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008U;
  }
  _impl_.receiver_account_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.receiver_account_.IsDefault()) {
    _impl_.receiver_account_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:transaction.Transaction.receiver_account)
}

// float amount = 5;
inline void Transaction::clear_amount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.amount_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100U;
}
inline float Transaction::amount() const {
  // @@protoc_insertion_point(field_get:transaction.Transaction.amount)
  return _internal_amount();
}
inline void Transaction::set_amount(float value) {
  _internal_set_amount(value);
  _impl_._has_bits_[0] |= 0x00000100U;
  // @@protoc_insertion_point(field_set:transaction.Transaction.amount)
}
inline float Transaction::_internal_amount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.amount_;
}
inline void Transaction::_internal_set_amount(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.amount_ = value;
}

// .transaction.Transaction.TransactionType transaction_type = 6;
inline void Transaction::clear_transaction_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transaction_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200U;
}
inline ::transaction::Transaction_TransactionType Transaction::transaction_type() const {
  // @@protoc_insertion_point(field_get:transaction.Transaction.transaction_type)
  return _internal_transaction_type();
}
inline void Transaction::set_transaction_type(::transaction::Transaction_TransactionType value) {
  _internal_set_transaction_type(value);
  _impl_._has_bits_[0] |= 0x00000200U;
  // @@protoc_insertion_point(field_set:transaction.Transaction.transaction_type)
}
inline ::transaction::Transaction_TransactionType Transaction::_internal_transaction_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transaction::Transaction_TransactionType>(_impl_.transaction_type_);
}
inline void Transaction::_internal_set_transaction_type(::transaction::Transaction_TransactionType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transaction_type_ = value;
}

// string merchant_category = 7;
inline void Transaction::clear_merchant_category() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.merchant_category_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010U;
}
inline const ::std::string& Transaction::merchant_category() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transaction.Transaction.merchant_category)
  return _internal_merchant_category();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_merchant_category(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010U;
  _impl_.merchant_category_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:transaction.Transaction.merchant_category)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_merchant_category()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_merchant_category();
  // @@protoc_insertion_point(field_mutable:transaction.Transaction.merchant_category)
  return _s;
}
inline const ::std::string& Transaction::_internal_merchant_category() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.merchant_category_.Get();
}
inline void Transaction::_internal_set_merchant_category(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010U;
  _impl_.merchant_category_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_merchant_category() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010U;
  return _impl_.merchant_category_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_merchant_category() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:transaction.Transaction.merchant_category)
  if ((_impl_._has_bits_[0] & 0x00000010U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010U;
  auto* released = _impl_.merchant_category_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.merchant_category_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_merchant_category(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010U;
  }
  _impl_.merchant_category_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.merchant_category_.IsDefault()) {
    _impl_.merchant_category_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:transaction.Transaction.merchant_category)
}

// string location = 8;
inline void Transaction::clear_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.location_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020U;
}
inline const ::std::string& Transaction::location() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transaction.Transaction.location)
  return _internal_location();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_location(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020U;
  _impl_.location_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:transaction.Transaction.location)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_location()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:transaction.Transaction.location)
  return _s;
}
inline const ::std::string& Transaction::_internal_location() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.location_.Get();
}
inline void Transaction::_internal_set_location(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020U;
  _impl_.location_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020U;
  return _impl_.location_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:transaction.Transaction.location)
  if ((_impl_._has_bits_[0] & 0x00000020U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020U;
  auto* released = _impl_.location_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.location_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_location(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020U;
  }
  _impl_.location_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.location_.IsDefault()) {
    _impl_.location_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:transaction.Transaction.location)
}

// .transaction.Transaction.DeviceUsed device_used = 9;
inline void Transaction::clear_device_used() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_used_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400U;
}
inline ::transaction::Transaction_DeviceUsed Transaction::device_used() const {
  // @@protoc_insertion_point(field_get:transaction.Transaction.device_used)
  return _internal_device_used();
}
inline void Transaction::set_device_used(::transaction::Transaction_DeviceUsed value) {
  _internal_set_device_used(value);
  _impl_._has_bits_[0] |= 0x00000400U;
  // @@protoc_insertion_point(field_set:transaction.Transaction.device_used)
}
inline ::transaction::Transaction_DeviceUsed Transaction::_internal_device_used() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transaction::Transaction_DeviceUsed>(_impl_.device_used_);
}
inline void Transaction::_internal_set_device_used(::transaction::Transaction_DeviceUsed value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_used_ = value;
}

// .transaction.Transaction.PaymentChannel payment_channel = 10;
inline void Transaction::clear_payment_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.payment_channel_ = 0;
  _impl_._has_bits_[0] &= ~0x00000800U;
}
inline ::transaction::Transaction_PaymentChannel Transaction::payment_channel() const {
  // @@protoc_insertion_point(field_get:transaction.Transaction.payment_channel)
  return _internal_payment_channel();
}
inline void Transaction::set_payment_channel(::transaction::Transaction_PaymentChannel value) {
  _internal_set_payment_channel(value);
  _impl_._has_bits_[0] |= 0x00000800U;
  // @@protoc_insertion_point(field_set:transaction.Transaction.payment_channel)
}
inline ::transaction::Transaction_PaymentChannel Transaction::_internal_payment_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::transaction::Transaction_PaymentChannel>(_impl_.payment_channel_);
}
inline void Transaction::_internal_set_payment_channel(::transaction::Transaction_PaymentChannel value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.payment_channel_ = value;
}

// string ip_address = 11;
inline void Transaction::clear_ip_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_address_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040U;
}
inline const ::std::string& Transaction::ip_address() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transaction.Transaction.ip_address)
  return _internal_ip_address();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_ip_address(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040U;
  _impl_.ip_address_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:transaction.Transaction.ip_address)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_ip_address()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_ip_address();
  // @@protoc_insertion_point(field_mutable:transaction.Transaction.ip_address)
  return _s;
}
inline const ::std::string& Transaction::_internal_ip_address() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_address_.Get();
}
inline void Transaction::_internal_set_ip_address(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040U;
  _impl_.ip_address_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_ip_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040U;
  return _impl_.ip_address_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_ip_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:transaction.Transaction.ip_address)
  if ((_impl_._has_bits_[0] & 0x00000040U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040U;
  auto* released = _impl_.ip_address_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ip_address_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_ip_address(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040U;
  }
  _impl_.ip_address_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:transaction.Transaction.ip_address)
}

// string device_hash = 12;
inline void Transaction::clear_device_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_hash_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000080U;
}
inline const ::std::string& Transaction::device_hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:transaction.Transaction.device_hash)
  return _internal_device_hash();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_device_hash(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080U;
  _impl_.device_hash_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:transaction.Transaction.device_hash)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_device_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_device_hash();
  // @@protoc_insertion_point(field_mutable:transaction.Transaction.device_hash)
  return _s;
}
inline const ::std::string& Transaction::_internal_device_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_hash_.Get();
}
inline void Transaction::_internal_set_device_hash(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080U;
  _impl_.device_hash_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_device_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080U;
  return _impl_.device_hash_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_device_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:transaction.Transaction.device_hash)
  if ((_impl_._has_bits_[0] & 0x00000080U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000080U;
  auto* released = _impl_.device_hash_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.device_hash_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_device_hash(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080U;
  }
  _impl_.device_hash_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.device_hash_.IsDefault()) {
    _impl_.device_hash_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:transaction.Transaction.device_hash)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace transaction


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::transaction::Transaction_TransactionType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::transaction::Transaction_TransactionType>() {
  return ::transaction::Transaction_TransactionType_descriptor();
}
template <>
struct is_proto_enum<::transaction::Transaction_DeviceUsed> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::transaction::Transaction_DeviceUsed>() {
  return ::transaction::Transaction_DeviceUsed_descriptor();
}
template <>
struct is_proto_enum<::transaction::Transaction_PaymentChannel> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::transaction::Transaction_PaymentChannel>() {
  return ::transaction::Transaction_PaymentChannel_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // transaction_2eproto_2epb_2eh
