# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\x1a\x1bgoogle/protobuf/empty.proto\"\xd1\x04\n\x0bTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0esender_account\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x18\n\x10receiver_account\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x02\x12\x42\n\x10transaction_type\x18\x06 \x01(\x0e\x32(.transaction.Transaction.TransactionType\x12\x19\n\x11merchant_category\x18\x07 \x01(\t\x12\x10\n\x08location\x18\x08 \x01(\t\x12\x38\n\x0b\x64\x65vice_used\x18\t \x01(\x0e\x32#.transaction.Transaction.DeviceUsed\x12@\n\x0fpayment_channel\x18\n \x01(\x0e\x32\'.transaction.Transaction.PaymentChannel\x12\x12\n\nip_address\x18\x0b \x01(\t\x12\x13\n\x0b\x64\x65vice_hash\x18\x0c \x01(\t\"I\n\x0fTransactionType\x12\x0e\n\nWITHDRAWAL\x10\x00\x12\x0b\n\x07\x44\x45POSIT\x10\x01\x12\x0c\n\x08TRANSFER\x10\x02\x12\x0b\n\x07PAYMENT\x10\x03\"3\n\nDeviceUsed\x12\n\n\x06MOBILE\x10\x00\x12\x07\n\x03\x41TM\x10\x01\x12\x07\n\x03POS\x10\x02\x12\x07\n\x03WEB\x10\x03\"?\n\x0ePaymentChannel\x12\x07\n\x03UPI\x10\x00\x12\x08\n\x04\x43\x41RD\x10\x01\x12\x07\n\x03\x41\x43H\x10\x02\x12\x11\n\rWIRE_TRANSFER\x10\x03\x32\\\n\x12TransactionService\x12\x46\n\x12ProcessTransaction\x12\x18.transaction.Transaction\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=64
  _globals['_TRANSACTION']._serialized_end=657
  _globals['_TRANSACTION_TRANSACTIONTYPE']._serialized_start=466
  _globals['_TRANSACTION_TRANSACTIONTYPE']._serialized_end=539
  _globals['_TRANSACTION_DEVICEUSED']._serialized_start=541
  _globals['_TRANSACTION_DEVICEUSED']._serialized_end=592
  _globals['_TRANSACTION_PAYMENTCHANNEL']._serialized_start=594
  _globals['_TRANSACTION_PAYMENTCHANNEL']._serialized_end=657
  _globals['_TRANSACTIONSERVICE']._serialized_start=659
  _globals['_TRANSACTIONSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
