// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rules/ml_rule.proto
// Protobuf C++ Version: 6.32.1

#include "rules/ml_rule.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rules {

inline constexpr MLRule::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        model_uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        lower_bound_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MLRule::MLRule(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MLRule_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MLRuleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MLRuleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MLRuleDefaultTypeInternal() {}
  union {
    MLRule _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MLRuleDefaultTypeInternal _MLRule_default_instance_;
}  // namespace rules
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_rules_2fml_5frule_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_rules_2fml_5frule_2eproto = nullptr;
const ::uint32_t
    TableStruct_rules_2fml_5frule_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rules::MLRule, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rules::MLRule, _impl_.model_uuid_),
        PROTOBUF_FIELD_OFFSET(::rules::MLRule, _impl_.lower_bound_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::rules::MLRule)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::rules::_MLRule_default_instance_._instance,
};
const char descriptor_table_protodef_rules_2fml_5frule_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023rules/ml_rule.proto\022\005rules\"1\n\006MLRule\022\022"
    "\n\nmodel_uuid\030\001 \001(\t\022\023\n\013lower_bound\030\002 \001(\001b"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_rules_2fml_5frule_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rules_2fml_5frule_2eproto = {
    false,
    false,
    87,
    descriptor_table_protodef_rules_2fml_5frule_2eproto,
    "rules/ml_rule.proto",
    &descriptor_table_rules_2fml_5frule_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_rules_2fml_5frule_2eproto::offsets,
    file_level_enum_descriptors_rules_2fml_5frule_2eproto,
    file_level_service_descriptors_rules_2fml_5frule_2eproto,
};
namespace rules {
// ===================================================================

class MLRule::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MLRule>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MLRule, _impl_._has_bits_);
};

MLRule::MLRule(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MLRule_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rules.MLRule)
}
PROTOBUF_NDEBUG_INLINE MLRule::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rules::MLRule& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        model_uuid_(arena, from.model_uuid_) {}

MLRule::MLRule(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MLRule& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MLRule_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MLRule* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.lower_bound_ = from._impl_.lower_bound_;

  // @@protoc_insertion_point(copy_constructor:rules.MLRule)
}
PROTOBUF_NDEBUG_INLINE MLRule::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        model_uuid_(arena) {}

inline void MLRule::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.lower_bound_ = {};
}
MLRule::~MLRule() {
  // @@protoc_insertion_point(destructor:rules.MLRule)
  SharedDtor(*this);
}
inline void MLRule::SharedDtor(MessageLite& self) {
  MLRule& this_ = static_cast<MLRule&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.model_uuid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MLRule::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MLRule(arena);
}
constexpr auto MLRule::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MLRule),
                                            alignof(MLRule));
}
constexpr auto MLRule::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MLRule_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MLRule::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MLRule>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MLRule::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MLRule>(), &MLRule::ByteSizeLong,
              &MLRule::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MLRule, _impl_._cached_size_),
          false,
      },
      &MLRule::kDescriptorMethods,
      &descriptor_table_rules_2fml_5frule_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MLRule_class_data_ =
        MLRule::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MLRule::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MLRule_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MLRule_class_data_.tc_table);
  return MLRule_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 31, 2>
MLRule::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MLRule, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MLRule_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rules::MLRule>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double lower_bound = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0, PROTOBUF_FIELD_OFFSET(MLRule, _impl_.lower_bound_)}},
    // string model_uuid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MLRule, _impl_.model_uuid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string model_uuid = 1;
    {PROTOBUF_FIELD_OFFSET(MLRule, _impl_.model_uuid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double lower_bound = 2;
    {PROTOBUF_FIELD_OFFSET(MLRule, _impl_.lower_bound_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\14\12\0\0\0\0\0\0"
    "rules.MLRule"
    "model_uuid"
  }},
};
PROTOBUF_NOINLINE void MLRule::Clear() {
// @@protoc_insertion_point(message_clear_start:rules.MLRule)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.model_uuid_.ClearNonDefaultToEmpty();
  }
  _impl_.lower_bound_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MLRule::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MLRule& this_ = static_cast<const MLRule&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MLRule::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MLRule& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rules.MLRule)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string model_uuid = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_model_uuid().empty()) {
      const ::std::string& _s = this_._internal_model_uuid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rules.MLRule.model_uuid");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // double lower_bound = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_lower_bound()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_lower_bound(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rules.MLRule)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MLRule::ByteSizeLong(const MessageLite& base) {
  const MLRule& this_ = static_cast<const MLRule&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MLRule::ByteSizeLong() const {
  const MLRule& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rules.MLRule)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // string model_uuid = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_model_uuid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_model_uuid());
      }
    }
    // double lower_bound = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_lower_bound()) != 0) {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MLRule::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MLRule*>(&to_msg);
  auto& from = static_cast<const MLRule&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:rules.MLRule)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_model_uuid().empty()) {
        _this->_internal_set_model_uuid(from._internal_model_uuid());
      } else {
        if (_this->_impl_.model_uuid_.IsDefault()) {
          _this->_internal_set_model_uuid("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_lower_bound()) != 0) {
        _this->_impl_.lower_bound_ = from._impl_.lower_bound_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MLRule::CopyFrom(const MLRule& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rules.MLRule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MLRule::InternalSwap(MLRule* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.model_uuid_, &other->_impl_.model_uuid_, arena);
  swap(_impl_.lower_bound_, other->_impl_.lower_bound_);
}

::google::protobuf::Metadata MLRule::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rules
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rules_2fml_5frule_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
