// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rules/pattern_rule.proto
// Protobuf C++ Version: 6.32.1

#include "rules/pattern_rule.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rules {

inline constexpr PatternRule::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        expression_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        max_delta_time_{0},
        max_count_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PatternRule::PatternRule(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PatternRule_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PatternRuleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PatternRuleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PatternRuleDefaultTypeInternal() {}
  union {
    PatternRule _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PatternRuleDefaultTypeInternal _PatternRule_default_instance_;
}  // namespace rules
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_rules_2fpattern_5frule_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_rules_2fpattern_5frule_2eproto = nullptr;
const ::uint32_t
    TableStruct_rules_2fpattern_5frule_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rules::PatternRule, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rules::PatternRule, _impl_.max_delta_time_),
        PROTOBUF_FIELD_OFFSET(::rules::PatternRule, _impl_.max_count_),
        PROTOBUF_FIELD_OFFSET(::rules::PatternRule, _impl_.expression_),
        1,
        2,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::rules::PatternRule)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::rules::_PatternRule_default_instance_._instance,
};
const char descriptor_table_protodef_rules_2fpattern_5frule_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030rules/pattern_rule.proto\022\005rules\"L\n\013Pat"
    "ternRule\022\026\n\016max_delta_time\030\001 \001(\005\022\021\n\tmax_"
    "count\030\002 \001(\005\022\022\n\nexpression\030\003 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_rules_2fpattern_5frule_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rules_2fpattern_5frule_2eproto = {
    false,
    false,
    119,
    descriptor_table_protodef_rules_2fpattern_5frule_2eproto,
    "rules/pattern_rule.proto",
    &descriptor_table_rules_2fpattern_5frule_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_rules_2fpattern_5frule_2eproto::offsets,
    file_level_enum_descriptors_rules_2fpattern_5frule_2eproto,
    file_level_service_descriptors_rules_2fpattern_5frule_2eproto,
};
namespace rules {
// ===================================================================

class PatternRule::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PatternRule>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PatternRule, _impl_._has_bits_);
};

PatternRule::PatternRule(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PatternRule_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rules.PatternRule)
}
PROTOBUF_NDEBUG_INLINE PatternRule::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rules::PatternRule& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        expression_(arena, from.expression_) {}

PatternRule::PatternRule(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PatternRule& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PatternRule_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PatternRule* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, max_delta_time_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, max_delta_time_),
           offsetof(Impl_, max_count_) -
               offsetof(Impl_, max_delta_time_) +
               sizeof(Impl_::max_count_));

  // @@protoc_insertion_point(copy_constructor:rules.PatternRule)
}
PROTOBUF_NDEBUG_INLINE PatternRule::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        expression_(arena) {}

inline void PatternRule::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, max_delta_time_),
           0,
           offsetof(Impl_, max_count_) -
               offsetof(Impl_, max_delta_time_) +
               sizeof(Impl_::max_count_));
}
PatternRule::~PatternRule() {
  // @@protoc_insertion_point(destructor:rules.PatternRule)
  SharedDtor(*this);
}
inline void PatternRule::SharedDtor(MessageLite& self) {
  PatternRule& this_ = static_cast<PatternRule&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.expression_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PatternRule::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PatternRule(arena);
}
constexpr auto PatternRule::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PatternRule),
                                            alignof(PatternRule));
}
constexpr auto PatternRule::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PatternRule_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PatternRule::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PatternRule>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PatternRule::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PatternRule>(), &PatternRule::ByteSizeLong,
              &PatternRule::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PatternRule, _impl_._cached_size_),
          false,
      },
      &PatternRule::kDescriptorMethods,
      &descriptor_table_rules_2fpattern_5frule_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PatternRule_class_data_ =
        PatternRule::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PatternRule::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PatternRule_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PatternRule_class_data_.tc_table);
  return PatternRule_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 36, 2>
PatternRule::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PatternRule, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PatternRule_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rules::PatternRule>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 max_delta_time = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PatternRule, _impl_.max_delta_time_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(PatternRule, _impl_.max_delta_time_)}},
    // int32 max_count = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PatternRule, _impl_.max_count_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(PatternRule, _impl_.max_count_)}},
    // string expression = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(PatternRule, _impl_.expression_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 max_delta_time = 1;
    {PROTOBUF_FIELD_OFFSET(PatternRule, _impl_.max_delta_time_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 max_count = 2;
    {PROTOBUF_FIELD_OFFSET(PatternRule, _impl_.max_count_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string expression = 3;
    {PROTOBUF_FIELD_OFFSET(PatternRule, _impl_.expression_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\0\12\0\0\0\0"
    "rules.PatternRule"
    "expression"
  }},
};
PROTOBUF_NOINLINE void PatternRule::Clear() {
// @@protoc_insertion_point(message_clear_start:rules.PatternRule)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.expression_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006U) != 0) {
    ::memset(&_impl_.max_delta_time_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.max_count_) -
        reinterpret_cast<char*>(&_impl_.max_delta_time_)) + sizeof(_impl_.max_count_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PatternRule::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PatternRule& this_ = static_cast<const PatternRule&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PatternRule::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PatternRule& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rules.PatternRule)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 max_delta_time = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_max_delta_time() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_max_delta_time(), target);
    }
  }

  // int32 max_count = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_max_count() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_max_count(), target);
    }
  }

  // string expression = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_expression().empty()) {
      const ::std::string& _s = this_._internal_expression();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rules.PatternRule.expression");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rules.PatternRule)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PatternRule::ByteSizeLong(const MessageLite& base) {
  const PatternRule& this_ = static_cast<const PatternRule&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PatternRule::ByteSizeLong() const {
  const PatternRule& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rules.PatternRule)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // string expression = 3;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_expression().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_expression());
      }
    }
    // int32 max_delta_time = 1;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_max_delta_time() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_max_delta_time());
      }
    }
    // int32 max_count = 2;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_max_count() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_max_count());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PatternRule::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PatternRule*>(&to_msg);
  auto& from = static_cast<const PatternRule&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:rules.PatternRule)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_expression().empty()) {
        _this->_internal_set_expression(from._internal_expression());
      } else {
        if (_this->_impl_.expression_.IsDefault()) {
          _this->_internal_set_expression("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_max_delta_time() != 0) {
        _this->_impl_.max_delta_time_ = from._impl_.max_delta_time_;
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_max_count() != 0) {
        _this->_impl_.max_count_ = from._impl_.max_count_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PatternRule::CopyFrom(const PatternRule& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rules.PatternRule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PatternRule::InternalSwap(PatternRule* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.expression_, &other->_impl_.expression_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PatternRule, _impl_.max_count_)
      + sizeof(PatternRule::_impl_.max_count_)
      - PROTOBUF_FIELD_OFFSET(PatternRule, _impl_.max_delta_time_)>(
          reinterpret_cast<char*>(&_impl_.max_delta_time_),
          reinterpret_cast<char*>(&other->_impl_.max_delta_time_));
}

::google::protobuf::Metadata PatternRule::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rules
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rules_2fpattern_5frule_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
