// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rule_config.proto
// Protobuf C++ Version: 6.32.1

#include "rule_config.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rules {

inline constexpr RuleConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rule_type_{static_cast< ::rules::RuleConfig_RuleType >(0)},
        is_critical_{false},
        rule_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR RuleConfig::RuleConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RuleConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RuleConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RuleConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RuleConfigDefaultTypeInternal() {}
  union {
    RuleConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RuleConfigDefaultTypeInternal _RuleConfig_default_instance_;
}  // namespace rules
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_rule_5fconfig_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_rule_5fconfig_2eproto = nullptr;
const ::uint32_t
    TableStruct_rule_5fconfig_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_._oneof_case_[0]),
        13, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.uuid_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.rule_type_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.is_critical_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.rule_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.rule_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.rule_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.rule_),
        PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_.rule_),
        0,
        1,
        2,
        3,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::rules::RuleConfig)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::rules::_RuleConfig_default_instance_._instance,
};
const char descriptor_table_protodef_rule_5fconfig_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021rule_config.proto\022\005rules\032\022pattern_rule"
    ".proto\032\024threshold_rule.proto\032\024composite_"
    "rule.proto\032\rml_rule.proto\"\341\002\n\nRuleConfig"
    "\022\014\n\004uuid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022-\n\trule_typ"
    "e\030\003 \001(\0162\032.rules.RuleConfig.RuleType\022\023\n\013i"
    "s_critical\030\004 \001(\010\022 \n\007ml_rule\030\005 \001(\0132\r.rule"
    "s.MLRuleH\000\022.\n\016composite_rule\030\006 \001(\0132\024.rul"
    "es.CompositeRuleH\000\022.\n\016threshold_rule\030\007 \001"
    "(\0132\024.rules.ThresholdRuleH\000\022*\n\014pattern_ru"
    "le\030\010 \001(\0132\022.rules.PatternRuleH\000\"=\n\010RuleTy"
    "pe\022\006\n\002ML\020\000\022\r\n\tCOMPOSITE\020\001\022\r\n\tTHRESHOLD\020\002"
    "\022\013\n\007PATTERN\020\003B\006\n\004ruleb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_rule_5fconfig_2eproto_deps[4] = {
        &::descriptor_table_composite_5frule_2eproto,
        &::descriptor_table_ml_5frule_2eproto,
        &::descriptor_table_pattern_5frule_2eproto,
        &::descriptor_table_threshold_5frule_2eproto,
};
static ::absl::once_flag descriptor_table_rule_5fconfig_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rule_5fconfig_2eproto = {
    false,
    false,
    469,
    descriptor_table_protodef_rule_5fconfig_2eproto,
    "rule_config.proto",
    &descriptor_table_rule_5fconfig_2eproto_once,
    descriptor_table_rule_5fconfig_2eproto_deps,
    4,
    1,
    schemas,
    file_default_instances,
    TableStruct_rule_5fconfig_2eproto::offsets,
    file_level_enum_descriptors_rule_5fconfig_2eproto,
    file_level_service_descriptors_rule_5fconfig_2eproto,
};
namespace rules {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RuleConfig_RuleType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rule_5fconfig_2eproto);
  return file_level_enum_descriptors_rule_5fconfig_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RuleConfig_RuleType_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class RuleConfig::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RuleConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::rules::RuleConfig, _impl_._oneof_case_);
};

void RuleConfig::set_allocated_ml_rule(::rules::MLRule* PROTOBUF_NULLABLE ml_rule) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_rule();
  if (ml_rule) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(ml_rule)->GetArena();
    if (message_arena != submessage_arena) {
      ml_rule = ::google::protobuf::internal::GetOwnedMessage(message_arena, ml_rule, submessage_arena);
    }
    set_has_ml_rule();
    _impl_.rule_.ml_rule_ = ml_rule;
  }
  // @@protoc_insertion_point(field_set_allocated:rules.RuleConfig.ml_rule)
}
void RuleConfig::clear_ml_rule() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (rule_case() == kMlRule) {
    if (GetArena() == nullptr) {
      delete _impl_.rule_.ml_rule_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.rule_.ml_rule_);
    }
    clear_has_rule();
  }
}
void RuleConfig::set_allocated_composite_rule(::rules::CompositeRule* PROTOBUF_NULLABLE composite_rule) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_rule();
  if (composite_rule) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(composite_rule)->GetArena();
    if (message_arena != submessage_arena) {
      composite_rule = ::google::protobuf::internal::GetOwnedMessage(message_arena, composite_rule, submessage_arena);
    }
    set_has_composite_rule();
    _impl_.rule_.composite_rule_ = composite_rule;
  }
  // @@protoc_insertion_point(field_set_allocated:rules.RuleConfig.composite_rule)
}
void RuleConfig::clear_composite_rule() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (rule_case() == kCompositeRule) {
    if (GetArena() == nullptr) {
      delete _impl_.rule_.composite_rule_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.rule_.composite_rule_);
    }
    clear_has_rule();
  }
}
void RuleConfig::set_allocated_threshold_rule(::rules::ThresholdRule* PROTOBUF_NULLABLE threshold_rule) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_rule();
  if (threshold_rule) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(threshold_rule)->GetArena();
    if (message_arena != submessage_arena) {
      threshold_rule = ::google::protobuf::internal::GetOwnedMessage(message_arena, threshold_rule, submessage_arena);
    }
    set_has_threshold_rule();
    _impl_.rule_.threshold_rule_ = threshold_rule;
  }
  // @@protoc_insertion_point(field_set_allocated:rules.RuleConfig.threshold_rule)
}
void RuleConfig::clear_threshold_rule() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (rule_case() == kThresholdRule) {
    if (GetArena() == nullptr) {
      delete _impl_.rule_.threshold_rule_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.rule_.threshold_rule_);
    }
    clear_has_rule();
  }
}
void RuleConfig::set_allocated_pattern_rule(::rules::PatternRule* PROTOBUF_NULLABLE pattern_rule) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_rule();
  if (pattern_rule) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(pattern_rule)->GetArena();
    if (message_arena != submessage_arena) {
      pattern_rule = ::google::protobuf::internal::GetOwnedMessage(message_arena, pattern_rule, submessage_arena);
    }
    set_has_pattern_rule();
    _impl_.rule_.pattern_rule_ = pattern_rule;
  }
  // @@protoc_insertion_point(field_set_allocated:rules.RuleConfig.pattern_rule)
}
void RuleConfig::clear_pattern_rule() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (rule_case() == kPatternRule) {
    if (GetArena() == nullptr) {
      delete _impl_.rule_.pattern_rule_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.rule_.pattern_rule_);
    }
    clear_has_rule();
  }
}
RuleConfig::RuleConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RuleConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rules.RuleConfig)
}
PROTOBUF_NDEBUG_INLINE RuleConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rules::RuleConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        uuid_(arena, from.uuid_),
        name_(arena, from.name_),
        rule_{},
        _oneof_case_{from._oneof_case_[0]} {}

RuleConfig::RuleConfig(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RuleConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RuleConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RuleConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, rule_type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, rule_type_),
           offsetof(Impl_, is_critical_) -
               offsetof(Impl_, rule_type_) +
               sizeof(Impl_::is_critical_));
  switch (rule_case()) {
    case RULE_NOT_SET:
      break;
      case kMlRule:
        _impl_.rule_.ml_rule_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.rule_.ml_rule_);
        break;
      case kCompositeRule:
        _impl_.rule_.composite_rule_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.rule_.composite_rule_);
        break;
      case kThresholdRule:
        _impl_.rule_.threshold_rule_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.rule_.threshold_rule_);
        break;
      case kPatternRule:
        _impl_.rule_.pattern_rule_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.rule_.pattern_rule_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:rules.RuleConfig)
}
PROTOBUF_NDEBUG_INLINE RuleConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        uuid_(arena),
        name_(arena),
        rule_{},
        _oneof_case_{} {}

inline void RuleConfig::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, rule_type_),
           0,
           offsetof(Impl_, is_critical_) -
               offsetof(Impl_, rule_type_) +
               sizeof(Impl_::is_critical_));
}
RuleConfig::~RuleConfig() {
  // @@protoc_insertion_point(destructor:rules.RuleConfig)
  SharedDtor(*this);
}
inline void RuleConfig::SharedDtor(MessageLite& self) {
  RuleConfig& this_ = static_cast<RuleConfig&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uuid_.Destroy();
  this_._impl_.name_.Destroy();
  if (this_.has_rule()) {
    this_.clear_rule();
  }
  this_._impl_.~Impl_();
}

void RuleConfig::clear_rule() {
// @@protoc_insertion_point(one_of_clear_start:rules.RuleConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (rule_case()) {
    case kMlRule: {
      if (GetArena() == nullptr) {
        delete _impl_.rule_.ml_rule_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.rule_.ml_rule_);
      }
      break;
    }
    case kCompositeRule: {
      if (GetArena() == nullptr) {
        delete _impl_.rule_.composite_rule_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.rule_.composite_rule_);
      }
      break;
    }
    case kThresholdRule: {
      if (GetArena() == nullptr) {
        delete _impl_.rule_.threshold_rule_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.rule_.threshold_rule_);
      }
      break;
    }
    case kPatternRule: {
      if (GetArena() == nullptr) {
        delete _impl_.rule_.pattern_rule_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.rule_.pattern_rule_);
      }
      break;
    }
    case RULE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = RULE_NOT_SET;
}


inline void* PROTOBUF_NONNULL RuleConfig::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RuleConfig(arena);
}
constexpr auto RuleConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RuleConfig),
                                            alignof(RuleConfig));
}
constexpr auto RuleConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RuleConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RuleConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RuleConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RuleConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RuleConfig>(), &RuleConfig::ByteSizeLong,
              &RuleConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_._cached_size_),
          false,
      },
      &RuleConfig::kDescriptorMethods,
      &descriptor_table_rule_5fconfig_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RuleConfig_class_data_ =
        RuleConfig::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RuleConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RuleConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RuleConfig_class_data_.tc_table);
  return RuleConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 8, 4, 41, 2>
RuleConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_._has_bits_),
    0, // no _extensions_
    8, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    RuleConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rules::RuleConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool is_critical = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RuleConfig, _impl_.is_critical_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.is_critical_)}},
    // string uuid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.uuid_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.name_)}},
    // .rules.RuleConfig.RuleType rule_type = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RuleConfig, _impl_.rule_type_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.rule_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string uuid = 1;
    {PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.uuid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .rules.RuleConfig.RuleType rule_type = 3;
    {PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.rule_type_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bool is_critical = 4;
    {PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.is_critical_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // .rules.MLRule ml_rule = 5;
    {PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.rule_.ml_rule_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rules.CompositeRule composite_rule = 6;
    {PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.rule_.composite_rule_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rules.ThresholdRule threshold_rule = 7;
    {PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.rule_.threshold_rule_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rules.PatternRule pattern_rule = 8;
    {PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.rule_.pattern_rule_), _Internal::kOneofCaseOffset + 0, 3, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::rules::MLRule>()},
      {::_pbi::TcParser::GetTable<::rules::CompositeRule>()},
      {::_pbi::TcParser::GetTable<::rules::ThresholdRule>()},
      {::_pbi::TcParser::GetTable<::rules::PatternRule>()},
  }},
  {{
    "\20\4\4\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "rules.RuleConfig"
    "uuid"
    "name"
  }},
};
PROTOBUF_NOINLINE void RuleConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:rules.RuleConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.uuid_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x0000000cU) != 0) {
    ::memset(&_impl_.rule_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.is_critical_) -
        reinterpret_cast<char*>(&_impl_.rule_type_)) + sizeof(_impl_.is_critical_));
  }
  clear_rule();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RuleConfig::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RuleConfig& this_ = static_cast<const RuleConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RuleConfig::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RuleConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rules.RuleConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string uuid = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_uuid().empty()) {
      const ::std::string& _s = this_._internal_uuid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rules.RuleConfig.uuid");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string name = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rules.RuleConfig.name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // .rules.RuleConfig.RuleType rule_type = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_rule_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          3, this_._internal_rule_type(), target);
    }
  }

  // bool is_critical = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008U) != 0) {
    if (this_._internal_is_critical() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_is_critical(), target);
    }
  }

  switch (this_.rule_case()) {
    case kMlRule: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *this_._impl_.rule_.ml_rule_, this_._impl_.rule_.ml_rule_->GetCachedSize(), target,
          stream);
      break;
    }
    case kCompositeRule: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, *this_._impl_.rule_.composite_rule_, this_._impl_.rule_.composite_rule_->GetCachedSize(), target,
          stream);
      break;
    }
    case kThresholdRule: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          7, *this_._impl_.rule_.threshold_rule_, this_._impl_.rule_.threshold_rule_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPatternRule: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          8, *this_._impl_.rule_.pattern_rule_, this_._impl_.rule_.pattern_rule_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rules.RuleConfig)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RuleConfig::ByteSizeLong(const MessageLite& base) {
  const RuleConfig& this_ = static_cast<const RuleConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RuleConfig::ByteSizeLong() const {
  const RuleConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rules.RuleConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    // string uuid = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_uuid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_uuid());
      }
    }
    // string name = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // .rules.RuleConfig.RuleType rule_type = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_rule_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_rule_type());
      }
    }
    // bool is_critical = 4;
    if ((cached_has_bits & 0x00000008U) != 0) {
      if (this_._internal_is_critical() != 0) {
        total_size += 2;
      }
    }
  }
  switch (this_.rule_case()) {
    // .rules.MLRule ml_rule = 5;
    case kMlRule: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rule_.ml_rule_);
      break;
    }
    // .rules.CompositeRule composite_rule = 6;
    case kCompositeRule: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rule_.composite_rule_);
      break;
    }
    // .rules.ThresholdRule threshold_rule = 7;
    case kThresholdRule: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rule_.threshold_rule_);
      break;
    }
    // .rules.PatternRule pattern_rule = 8;
    case kPatternRule: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rule_.pattern_rule_);
      break;
    }
    case RULE_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RuleConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RuleConfig*>(&to_msg);
  auto& from = static_cast<const RuleConfig&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rules.RuleConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_uuid().empty()) {
        _this->_internal_set_uuid(from._internal_uuid());
      } else {
        if (_this->_impl_.uuid_.IsDefault()) {
          _this->_internal_set_uuid("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_rule_type() != 0) {
        _this->_impl_.rule_type_ = from._impl_.rule_type_;
      }
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      if (from._internal_is_critical() != 0) {
        _this->_impl_.is_critical_ = from._impl_.is_critical_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_rule();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kMlRule: {
        if (oneof_needs_init) {
          _this->_impl_.rule_.ml_rule_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.rule_.ml_rule_);
        } else {
          _this->_impl_.rule_.ml_rule_->MergeFrom(*from._impl_.rule_.ml_rule_);
        }
        break;
      }
      case kCompositeRule: {
        if (oneof_needs_init) {
          _this->_impl_.rule_.composite_rule_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.rule_.composite_rule_);
        } else {
          _this->_impl_.rule_.composite_rule_->MergeFrom(*from._impl_.rule_.composite_rule_);
        }
        break;
      }
      case kThresholdRule: {
        if (oneof_needs_init) {
          _this->_impl_.rule_.threshold_rule_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.rule_.threshold_rule_);
        } else {
          _this->_impl_.rule_.threshold_rule_->MergeFrom(*from._impl_.rule_.threshold_rule_);
        }
        break;
      }
      case kPatternRule: {
        if (oneof_needs_init) {
          _this->_impl_.rule_.pattern_rule_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.rule_.pattern_rule_);
        } else {
          _this->_impl_.rule_.pattern_rule_->MergeFrom(*from._impl_.rule_.pattern_rule_);
        }
        break;
      }
      case RULE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RuleConfig::CopyFrom(const RuleConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rules.RuleConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RuleConfig::InternalSwap(RuleConfig* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uuid_, &other->_impl_.uuid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.is_critical_)
      + sizeof(RuleConfig::_impl_.is_critical_)
      - PROTOBUF_FIELD_OFFSET(RuleConfig, _impl_.rule_type_)>(
          reinterpret_cast<char*>(&_impl_.rule_type_),
          reinterpret_cast<char*>(&other->_impl_.rule_type_));
  swap(_impl_.rule_, other->_impl_.rule_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata RuleConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rules
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rule_5fconfig_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
