// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rules/rule_config.proto
// Protobuf C++ Version: 6.32.1

#ifndef rules_2frule_5fconfig_2eproto_2epb_2eh
#define rules_2frule_5fconfig_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "rules/pattern_rule.pb.h"
#include "rules/threshold_rule.pb.h"
#include "rules/composite_rule.pb.h"
#include "rules/ml_rule.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rules_2frule_5fconfig_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rules_2frule_5fconfig_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_rules_2frule_5fconfig_2eproto;
}  // extern "C"
namespace rules {
enum RuleConfig_RuleType : int;
extern const uint32_t RuleConfig_RuleType_internal_data_[];
class RuleConfig;
struct RuleConfigDefaultTypeInternal;
extern RuleConfigDefaultTypeInternal _RuleConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RuleConfig_class_data_;
}  // namespace rules
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::rules::RuleConfig_RuleType_internal_data_>
    internal::EnumTraitsImpl::value<::rules::RuleConfig_RuleType>;
}  // namespace protobuf
}  // namespace google

namespace rules {
enum RuleConfig_RuleType : int {
  RuleConfig_RuleType_ML = 0,
  RuleConfig_RuleType_COMPOSITE = 1,
  RuleConfig_RuleType_THRESHOLD = 2,
  RuleConfig_RuleType_PATTERN = 3,
  RuleConfig_RuleType_RuleConfig_RuleType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RuleConfig_RuleType_RuleConfig_RuleType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RuleConfig_RuleType_internal_data_[];
inline constexpr RuleConfig_RuleType RuleConfig_RuleType_RuleType_MIN =
    static_cast<RuleConfig_RuleType>(0);
inline constexpr RuleConfig_RuleType RuleConfig_RuleType_RuleType_MAX =
    static_cast<RuleConfig_RuleType>(3);
inline bool RuleConfig_RuleType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int RuleConfig_RuleType_RuleType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RuleConfig_RuleType_descriptor();
template <typename T>
const ::std::string& RuleConfig_RuleType_Name(T value) {
  static_assert(::std::is_same<T, RuleConfig_RuleType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RuleType_Name().");
  return RuleConfig_RuleType_Name(static_cast<RuleConfig_RuleType>(value));
}
template <>
inline const ::std::string& RuleConfig_RuleType_Name(RuleConfig_RuleType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RuleConfig_RuleType_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool RuleConfig_RuleType_Parse(
    ::absl::string_view name, RuleConfig_RuleType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RuleConfig_RuleType>(RuleConfig_RuleType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RuleConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rules.RuleConfig) */ {
 public:
  inline RuleConfig() : RuleConfig(nullptr) {}
  ~RuleConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RuleConfig* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RuleConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RuleConfig(::google::protobuf::internal::ConstantInitialized);

  inline RuleConfig(const RuleConfig& from) : RuleConfig(nullptr, from) {}
  inline RuleConfig(RuleConfig&& from) noexcept
      : RuleConfig(nullptr, ::std::move(from)) {}
  inline RuleConfig& operator=(const RuleConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline RuleConfig& operator=(RuleConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RuleConfig& default_instance() {
    return *reinterpret_cast<const RuleConfig*>(
        &_RuleConfig_default_instance_);
  }
  enum RuleCase {
    kMlRule = 5,
    kCompositeRule = 6,
    kThresholdRule = 7,
    kPatternRule = 8,
    RULE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RuleConfig& a, RuleConfig& b) { a.Swap(&b); }
  inline void Swap(RuleConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RuleConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RuleConfig* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RuleConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RuleConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RuleConfig& from) { RuleConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RuleConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "rules.RuleConfig"; }

 protected:
  explicit RuleConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RuleConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RuleConfig& from);
  RuleConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RuleConfig&& from) noexcept
      : RuleConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using RuleType = RuleConfig_RuleType;
  static constexpr RuleType ML = RuleConfig_RuleType_ML;
  static constexpr RuleType COMPOSITE = RuleConfig_RuleType_COMPOSITE;
  static constexpr RuleType THRESHOLD = RuleConfig_RuleType_THRESHOLD;
  static constexpr RuleType PATTERN = RuleConfig_RuleType_PATTERN;
  static inline bool RuleType_IsValid(int value) {
    return RuleConfig_RuleType_IsValid(value);
  }
  static constexpr RuleType RuleType_MIN = RuleConfig_RuleType_RuleType_MIN;
  static constexpr RuleType RuleType_MAX = RuleConfig_RuleType_RuleType_MAX;
  static constexpr int RuleType_ARRAYSIZE = RuleConfig_RuleType_RuleType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RuleType_descriptor() {
    return RuleConfig_RuleType_descriptor();
  }
  template <typename T>
  static inline const ::std::string& RuleType_Name(T value) {
    return RuleConfig_RuleType_Name(value);
  }
  static inline bool RuleType_Parse(
      ::absl::string_view name, RuleType* PROTOBUF_NONNULL value) {
    return RuleConfig_RuleType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 1,
    kNameFieldNumber = 2,
    kRuleTypeFieldNumber = 3,
    kIsCriticalFieldNumber = 4,
    kMlRuleFieldNumber = 5,
    kCompositeRuleFieldNumber = 6,
    kThresholdRuleFieldNumber = 7,
    kPatternRuleFieldNumber = 8,
  };
  // string uuid = 1;
  void clear_uuid() ;
  const ::std::string& uuid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uuid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uuid();
  void set_allocated_uuid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uuid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uuid();

  public:
  // string name = 2;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // .rules.RuleConfig.RuleType rule_type = 3;
  void clear_rule_type() ;
  ::rules::RuleConfig_RuleType rule_type() const;
  void set_rule_type(::rules::RuleConfig_RuleType value);

  private:
  ::rules::RuleConfig_RuleType _internal_rule_type() const;
  void _internal_set_rule_type(::rules::RuleConfig_RuleType value);

  public:
  // bool is_critical = 4;
  void clear_is_critical() ;
  bool is_critical() const;
  void set_is_critical(bool value);

  private:
  bool _internal_is_critical() const;
  void _internal_set_is_critical(bool value);

  public:
  // .rules.MLRule ml_rule = 5;
  bool has_ml_rule() const;
  private:
  bool _internal_has_ml_rule() const;

  public:
  void clear_ml_rule() ;
  const ::rules::MLRule& ml_rule() const;
  [[nodiscard]] ::rules::MLRule* PROTOBUF_NULLABLE release_ml_rule();
  ::rules::MLRule* PROTOBUF_NONNULL mutable_ml_rule();
  void set_allocated_ml_rule(::rules::MLRule* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_ml_rule(::rules::MLRule* PROTOBUF_NULLABLE value);
  ::rules::MLRule* PROTOBUF_NULLABLE unsafe_arena_release_ml_rule();

  private:
  const ::rules::MLRule& _internal_ml_rule() const;
  ::rules::MLRule* PROTOBUF_NONNULL _internal_mutable_ml_rule();

  public:
  // .rules.CompositeRule composite_rule = 6;
  bool has_composite_rule() const;
  private:
  bool _internal_has_composite_rule() const;

  public:
  void clear_composite_rule() ;
  const ::rules::CompositeRule& composite_rule() const;
  [[nodiscard]] ::rules::CompositeRule* PROTOBUF_NULLABLE release_composite_rule();
  ::rules::CompositeRule* PROTOBUF_NONNULL mutable_composite_rule();
  void set_allocated_composite_rule(::rules::CompositeRule* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_composite_rule(::rules::CompositeRule* PROTOBUF_NULLABLE value);
  ::rules::CompositeRule* PROTOBUF_NULLABLE unsafe_arena_release_composite_rule();

  private:
  const ::rules::CompositeRule& _internal_composite_rule() const;
  ::rules::CompositeRule* PROTOBUF_NONNULL _internal_mutable_composite_rule();

  public:
  // .rules.ThresholdRule threshold_rule = 7;
  bool has_threshold_rule() const;
  private:
  bool _internal_has_threshold_rule() const;

  public:
  void clear_threshold_rule() ;
  const ::rules::ThresholdRule& threshold_rule() const;
  [[nodiscard]] ::rules::ThresholdRule* PROTOBUF_NULLABLE release_threshold_rule();
  ::rules::ThresholdRule* PROTOBUF_NONNULL mutable_threshold_rule();
  void set_allocated_threshold_rule(::rules::ThresholdRule* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_threshold_rule(::rules::ThresholdRule* PROTOBUF_NULLABLE value);
  ::rules::ThresholdRule* PROTOBUF_NULLABLE unsafe_arena_release_threshold_rule();

  private:
  const ::rules::ThresholdRule& _internal_threshold_rule() const;
  ::rules::ThresholdRule* PROTOBUF_NONNULL _internal_mutable_threshold_rule();

  public:
  // .rules.PatternRule pattern_rule = 8;
  bool has_pattern_rule() const;
  private:
  bool _internal_has_pattern_rule() const;

  public:
  void clear_pattern_rule() ;
  const ::rules::PatternRule& pattern_rule() const;
  [[nodiscard]] ::rules::PatternRule* PROTOBUF_NULLABLE release_pattern_rule();
  ::rules::PatternRule* PROTOBUF_NONNULL mutable_pattern_rule();
  void set_allocated_pattern_rule(::rules::PatternRule* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_pattern_rule(::rules::PatternRule* PROTOBUF_NULLABLE value);
  ::rules::PatternRule* PROTOBUF_NULLABLE unsafe_arena_release_pattern_rule();

  private:
  const ::rules::PatternRule& _internal_pattern_rule() const;
  ::rules::PatternRule* PROTOBUF_NONNULL _internal_mutable_pattern_rule();

  public:
  void clear_rule();
  RuleCase rule_case() const;
  // @@protoc_insertion_point(class_scope:rules.RuleConfig)
 private:
  class _Internal;
  void set_has_ml_rule();
  void set_has_composite_rule();
  void set_has_threshold_rule();
  void set_has_pattern_rule();
  inline bool has_rule() const;
  inline void clear_has_rule();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 8,
                                   4, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RuleConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    int rule_type_;
    bool is_critical_;
    union RuleUnion {
      constexpr RuleUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE ml_rule_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE composite_rule_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE threshold_rule_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE pattern_rule_;
    } rule_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rules_2frule_5fconfig_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RuleConfig_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RuleConfig

// string uuid = 1;
inline void RuleConfig::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& RuleConfig::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rules.RuleConfig.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RuleConfig::set_uuid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rules.RuleConfig.uuid)
}
inline ::std::string* PROTOBUF_NONNULL RuleConfig::mutable_uuid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:rules.RuleConfig.uuid)
  return _s;
}
inline const ::std::string& RuleConfig::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void RuleConfig::_internal_set_uuid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.uuid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RuleConfig::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.uuid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RuleConfig::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rules.RuleConfig.uuid)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.uuid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uuid_.Set("", GetArena());
  }
  return released;
}
inline void RuleConfig::set_allocated_uuid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:rules.RuleConfig.uuid)
}

// string name = 2;
inline void RuleConfig::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& RuleConfig::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rules.RuleConfig.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RuleConfig::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rules.RuleConfig.name)
}
inline ::std::string* PROTOBUF_NONNULL RuleConfig::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:rules.RuleConfig.name)
  return _s;
}
inline const ::std::string& RuleConfig::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void RuleConfig::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RuleConfig::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RuleConfig::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rules.RuleConfig.name)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void RuleConfig::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:rules.RuleConfig.name)
}

// .rules.RuleConfig.RuleType rule_type = 3;
inline void RuleConfig::clear_rule_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::rules::RuleConfig_RuleType RuleConfig::rule_type() const {
  // @@protoc_insertion_point(field_get:rules.RuleConfig.rule_type)
  return _internal_rule_type();
}
inline void RuleConfig::set_rule_type(::rules::RuleConfig_RuleType value) {
  _internal_set_rule_type(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:rules.RuleConfig.rule_type)
}
inline ::rules::RuleConfig_RuleType RuleConfig::_internal_rule_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::rules::RuleConfig_RuleType>(_impl_.rule_type_);
}
inline void RuleConfig::_internal_set_rule_type(::rules::RuleConfig_RuleType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_type_ = value;
}

// bool is_critical = 4;
inline void RuleConfig::clear_is_critical() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_critical_ = false;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline bool RuleConfig::is_critical() const {
  // @@protoc_insertion_point(field_get:rules.RuleConfig.is_critical)
  return _internal_is_critical();
}
inline void RuleConfig::set_is_critical(bool value) {
  _internal_set_is_critical(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:rules.RuleConfig.is_critical)
}
inline bool RuleConfig::_internal_is_critical() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_critical_;
}
inline void RuleConfig::_internal_set_is_critical(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_critical_ = value;
}

// .rules.MLRule ml_rule = 5;
inline bool RuleConfig::has_ml_rule() const {
  return rule_case() == kMlRule;
}
inline bool RuleConfig::_internal_has_ml_rule() const {
  return rule_case() == kMlRule;
}
inline void RuleConfig::set_has_ml_rule() {
  _impl_._oneof_case_[0] = kMlRule;
}
inline ::rules::MLRule* PROTOBUF_NULLABLE RuleConfig::release_ml_rule() {
  // @@protoc_insertion_point(field_release:rules.RuleConfig.ml_rule)
  if (rule_case() == kMlRule) {
    clear_has_rule();
    auto* temp = reinterpret_cast<::rules::MLRule*>(_impl_.rule_.ml_rule_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.rule_.ml_rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rules::MLRule& RuleConfig::_internal_ml_rule() const {
  return rule_case() == kMlRule ? *reinterpret_cast<::rules::MLRule*>(_impl_.rule_.ml_rule_) : reinterpret_cast<::rules::MLRule&>(::rules::_MLRule_default_instance_);
}
inline const ::rules::MLRule& RuleConfig::ml_rule() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rules.RuleConfig.ml_rule)
  return _internal_ml_rule();
}
inline ::rules::MLRule* PROTOBUF_NULLABLE RuleConfig::unsafe_arena_release_ml_rule() {
  // @@protoc_insertion_point(field_unsafe_arena_release:rules.RuleConfig.ml_rule)
  if (rule_case() == kMlRule) {
    clear_has_rule();
    auto* temp = reinterpret_cast<::rules::MLRule*>(_impl_.rule_.ml_rule_);
    _impl_.rule_.ml_rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RuleConfig::unsafe_arena_set_allocated_ml_rule(
    ::rules::MLRule* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_rule();
  if (value) {
    set_has_ml_rule();
    _impl_.rule_.ml_rule_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rules.RuleConfig.ml_rule)
}
inline ::rules::MLRule* PROTOBUF_NONNULL RuleConfig::_internal_mutable_ml_rule() {
  if (rule_case() != kMlRule) {
    clear_rule();
    set_has_ml_rule();
    _impl_.rule_.ml_rule_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::rules::MLRule>(GetArena()));
  }
  return reinterpret_cast<::rules::MLRule*>(_impl_.rule_.ml_rule_);
}
inline ::rules::MLRule* PROTOBUF_NONNULL RuleConfig::mutable_ml_rule()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::rules::MLRule* _msg = _internal_mutable_ml_rule();
  // @@protoc_insertion_point(field_mutable:rules.RuleConfig.ml_rule)
  return _msg;
}

// .rules.CompositeRule composite_rule = 6;
inline bool RuleConfig::has_composite_rule() const {
  return rule_case() == kCompositeRule;
}
inline bool RuleConfig::_internal_has_composite_rule() const {
  return rule_case() == kCompositeRule;
}
inline void RuleConfig::set_has_composite_rule() {
  _impl_._oneof_case_[0] = kCompositeRule;
}
inline ::rules::CompositeRule* PROTOBUF_NULLABLE RuleConfig::release_composite_rule() {
  // @@protoc_insertion_point(field_release:rules.RuleConfig.composite_rule)
  if (rule_case() == kCompositeRule) {
    clear_has_rule();
    auto* temp = reinterpret_cast<::rules::CompositeRule*>(_impl_.rule_.composite_rule_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.rule_.composite_rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rules::CompositeRule& RuleConfig::_internal_composite_rule() const {
  return rule_case() == kCompositeRule ? *reinterpret_cast<::rules::CompositeRule*>(_impl_.rule_.composite_rule_) : reinterpret_cast<::rules::CompositeRule&>(::rules::_CompositeRule_default_instance_);
}
inline const ::rules::CompositeRule& RuleConfig::composite_rule() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rules.RuleConfig.composite_rule)
  return _internal_composite_rule();
}
inline ::rules::CompositeRule* PROTOBUF_NULLABLE RuleConfig::unsafe_arena_release_composite_rule() {
  // @@protoc_insertion_point(field_unsafe_arena_release:rules.RuleConfig.composite_rule)
  if (rule_case() == kCompositeRule) {
    clear_has_rule();
    auto* temp = reinterpret_cast<::rules::CompositeRule*>(_impl_.rule_.composite_rule_);
    _impl_.rule_.composite_rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RuleConfig::unsafe_arena_set_allocated_composite_rule(
    ::rules::CompositeRule* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_rule();
  if (value) {
    set_has_composite_rule();
    _impl_.rule_.composite_rule_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rules.RuleConfig.composite_rule)
}
inline ::rules::CompositeRule* PROTOBUF_NONNULL RuleConfig::_internal_mutable_composite_rule() {
  if (rule_case() != kCompositeRule) {
    clear_rule();
    set_has_composite_rule();
    _impl_.rule_.composite_rule_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::rules::CompositeRule>(GetArena()));
  }
  return reinterpret_cast<::rules::CompositeRule*>(_impl_.rule_.composite_rule_);
}
inline ::rules::CompositeRule* PROTOBUF_NONNULL RuleConfig::mutable_composite_rule()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::rules::CompositeRule* _msg = _internal_mutable_composite_rule();
  // @@protoc_insertion_point(field_mutable:rules.RuleConfig.composite_rule)
  return _msg;
}

// .rules.ThresholdRule threshold_rule = 7;
inline bool RuleConfig::has_threshold_rule() const {
  return rule_case() == kThresholdRule;
}
inline bool RuleConfig::_internal_has_threshold_rule() const {
  return rule_case() == kThresholdRule;
}
inline void RuleConfig::set_has_threshold_rule() {
  _impl_._oneof_case_[0] = kThresholdRule;
}
inline ::rules::ThresholdRule* PROTOBUF_NULLABLE RuleConfig::release_threshold_rule() {
  // @@protoc_insertion_point(field_release:rules.RuleConfig.threshold_rule)
  if (rule_case() == kThresholdRule) {
    clear_has_rule();
    auto* temp = reinterpret_cast<::rules::ThresholdRule*>(_impl_.rule_.threshold_rule_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.rule_.threshold_rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rules::ThresholdRule& RuleConfig::_internal_threshold_rule() const {
  return rule_case() == kThresholdRule ? *reinterpret_cast<::rules::ThresholdRule*>(_impl_.rule_.threshold_rule_) : reinterpret_cast<::rules::ThresholdRule&>(::rules::_ThresholdRule_default_instance_);
}
inline const ::rules::ThresholdRule& RuleConfig::threshold_rule() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rules.RuleConfig.threshold_rule)
  return _internal_threshold_rule();
}
inline ::rules::ThresholdRule* PROTOBUF_NULLABLE RuleConfig::unsafe_arena_release_threshold_rule() {
  // @@protoc_insertion_point(field_unsafe_arena_release:rules.RuleConfig.threshold_rule)
  if (rule_case() == kThresholdRule) {
    clear_has_rule();
    auto* temp = reinterpret_cast<::rules::ThresholdRule*>(_impl_.rule_.threshold_rule_);
    _impl_.rule_.threshold_rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RuleConfig::unsafe_arena_set_allocated_threshold_rule(
    ::rules::ThresholdRule* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_rule();
  if (value) {
    set_has_threshold_rule();
    _impl_.rule_.threshold_rule_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rules.RuleConfig.threshold_rule)
}
inline ::rules::ThresholdRule* PROTOBUF_NONNULL RuleConfig::_internal_mutable_threshold_rule() {
  if (rule_case() != kThresholdRule) {
    clear_rule();
    set_has_threshold_rule();
    _impl_.rule_.threshold_rule_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::rules::ThresholdRule>(GetArena()));
  }
  return reinterpret_cast<::rules::ThresholdRule*>(_impl_.rule_.threshold_rule_);
}
inline ::rules::ThresholdRule* PROTOBUF_NONNULL RuleConfig::mutable_threshold_rule()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::rules::ThresholdRule* _msg = _internal_mutable_threshold_rule();
  // @@protoc_insertion_point(field_mutable:rules.RuleConfig.threshold_rule)
  return _msg;
}

// .rules.PatternRule pattern_rule = 8;
inline bool RuleConfig::has_pattern_rule() const {
  return rule_case() == kPatternRule;
}
inline bool RuleConfig::_internal_has_pattern_rule() const {
  return rule_case() == kPatternRule;
}
inline void RuleConfig::set_has_pattern_rule() {
  _impl_._oneof_case_[0] = kPatternRule;
}
inline ::rules::PatternRule* PROTOBUF_NULLABLE RuleConfig::release_pattern_rule() {
  // @@protoc_insertion_point(field_release:rules.RuleConfig.pattern_rule)
  if (rule_case() == kPatternRule) {
    clear_has_rule();
    auto* temp = reinterpret_cast<::rules::PatternRule*>(_impl_.rule_.pattern_rule_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.rule_.pattern_rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rules::PatternRule& RuleConfig::_internal_pattern_rule() const {
  return rule_case() == kPatternRule ? *reinterpret_cast<::rules::PatternRule*>(_impl_.rule_.pattern_rule_) : reinterpret_cast<::rules::PatternRule&>(::rules::_PatternRule_default_instance_);
}
inline const ::rules::PatternRule& RuleConfig::pattern_rule() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rules.RuleConfig.pattern_rule)
  return _internal_pattern_rule();
}
inline ::rules::PatternRule* PROTOBUF_NULLABLE RuleConfig::unsafe_arena_release_pattern_rule() {
  // @@protoc_insertion_point(field_unsafe_arena_release:rules.RuleConfig.pattern_rule)
  if (rule_case() == kPatternRule) {
    clear_has_rule();
    auto* temp = reinterpret_cast<::rules::PatternRule*>(_impl_.rule_.pattern_rule_);
    _impl_.rule_.pattern_rule_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void RuleConfig::unsafe_arena_set_allocated_pattern_rule(
    ::rules::PatternRule* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_rule();
  if (value) {
    set_has_pattern_rule();
    _impl_.rule_.pattern_rule_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rules.RuleConfig.pattern_rule)
}
inline ::rules::PatternRule* PROTOBUF_NONNULL RuleConfig::_internal_mutable_pattern_rule() {
  if (rule_case() != kPatternRule) {
    clear_rule();
    set_has_pattern_rule();
    _impl_.rule_.pattern_rule_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::rules::PatternRule>(GetArena()));
  }
  return reinterpret_cast<::rules::PatternRule*>(_impl_.rule_.pattern_rule_);
}
inline ::rules::PatternRule* PROTOBUF_NONNULL RuleConfig::mutable_pattern_rule()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::rules::PatternRule* _msg = _internal_mutable_pattern_rule();
  // @@protoc_insertion_point(field_mutable:rules.RuleConfig.pattern_rule)
  return _msg;
}

inline bool RuleConfig::has_rule() const {
  return rule_case() != RULE_NOT_SET;
}
inline void RuleConfig::clear_has_rule() {
  _impl_._oneof_case_[0] = RULE_NOT_SET;
}
inline RuleConfig::RuleCase RuleConfig::rule_case() const {
  return RuleConfig::RuleCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace rules


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::rules::RuleConfig_RuleType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::rules::RuleConfig_RuleType>() {
  return ::rules::RuleConfig_RuleType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // rules_2frule_5fconfig_2eproto_2epb_2eh
