// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: threshold_rule.proto
// Protobuf C++ Version: 6.32.1

#ifndef threshold_5frule_2eproto_2epb_2eh
#define threshold_5frule_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_threshold_5frule_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_threshold_5frule_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_threshold_5frule_2eproto;
}  // extern "C"
namespace rules {
class ThresholdRule;
struct ThresholdRuleDefaultTypeInternal;
extern ThresholdRuleDefaultTypeInternal _ThresholdRule_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ThresholdRule_class_data_;
}  // namespace rules
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace rules {

// ===================================================================


// -------------------------------------------------------------------

class ThresholdRule final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rules.ThresholdRule) */ {
 public:
  inline ThresholdRule() : ThresholdRule(nullptr) {}
  ~ThresholdRule() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ThresholdRule* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ThresholdRule));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ThresholdRule(::google::protobuf::internal::ConstantInitialized);

  inline ThresholdRule(const ThresholdRule& from) : ThresholdRule(nullptr, from) {}
  inline ThresholdRule(ThresholdRule&& from) noexcept
      : ThresholdRule(nullptr, ::std::move(from)) {}
  inline ThresholdRule& operator=(const ThresholdRule& from) {
    CopyFrom(from);
    return *this;
  }
  inline ThresholdRule& operator=(ThresholdRule&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ThresholdRule& default_instance() {
    return *reinterpret_cast<const ThresholdRule*>(
        &_ThresholdRule_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ThresholdRule& a, ThresholdRule& b) { a.Swap(&b); }
  inline void Swap(ThresholdRule* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ThresholdRule* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ThresholdRule* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ThresholdRule>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ThresholdRule& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ThresholdRule& from) { ThresholdRule::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ThresholdRule* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "rules.ThresholdRule"; }

 protected:
  explicit ThresholdRule(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ThresholdRule(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ThresholdRule& from);
  ThresholdRule(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ThresholdRule&& from) noexcept
      : ThresholdRule(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExpressionFieldNumber = 1,
  };
  // string expression = 1;
  void clear_expression() ;
  const ::std::string& expression() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_expression(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_expression();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_expression();
  void set_allocated_expression(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_expression() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_expression(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_expression();

  public:
  // @@protoc_insertion_point(class_scope:rules.ThresholdRule)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 38,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ThresholdRule& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr expression_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_threshold_5frule_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ThresholdRule_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ThresholdRule

// string expression = 1;
inline void ThresholdRule::clear_expression() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expression_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& ThresholdRule::expression() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rules.ThresholdRule.expression)
  return _internal_expression();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ThresholdRule::set_expression(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.expression_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rules.ThresholdRule.expression)
}
inline ::std::string* PROTOBUF_NONNULL ThresholdRule::mutable_expression()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_expression();
  // @@protoc_insertion_point(field_mutable:rules.ThresholdRule.expression)
  return _s;
}
inline const ::std::string& ThresholdRule::_internal_expression() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.expression_.Get();
}
inline void ThresholdRule::_internal_set_expression(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.expression_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ThresholdRule::_internal_mutable_expression() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.expression_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ThresholdRule::release_expression() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rules.ThresholdRule.expression)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.expression_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.expression_.Set("", GetArena());
  }
  return released;
}
inline void ThresholdRule::set_allocated_expression(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.expression_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.expression_.IsDefault()) {
    _impl_.expression_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:rules.ThresholdRule.expression)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace rules


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // threshold_5frule_2eproto_2epb_2eh
