// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rules/threshold_rule.proto
// Protobuf C++ Version: 6.32.1

#include "rules/threshold_rule.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rules {

inline constexpr ThresholdRule::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        expression_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ThresholdRule::ThresholdRule(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ThresholdRule_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ThresholdRuleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ThresholdRuleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ThresholdRuleDefaultTypeInternal() {}
  union {
    ThresholdRule _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ThresholdRuleDefaultTypeInternal _ThresholdRule_default_instance_;
}  // namespace rules
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_rules_2fthreshold_5frule_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_rules_2fthreshold_5frule_2eproto = nullptr;
const ::uint32_t
    TableStruct_rules_2fthreshold_5frule_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rules::ThresholdRule, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rules::ThresholdRule, _impl_.expression_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::rules::ThresholdRule)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::rules::_ThresholdRule_default_instance_._instance,
};
const char descriptor_table_protodef_rules_2fthreshold_5frule_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032rules/threshold_rule.proto\022\005rules\"#\n\rT"
    "hresholdRule\022\022\n\nexpression\030\001 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_rules_2fthreshold_5frule_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rules_2fthreshold_5frule_2eproto = {
    false,
    false,
    80,
    descriptor_table_protodef_rules_2fthreshold_5frule_2eproto,
    "rules/threshold_rule.proto",
    &descriptor_table_rules_2fthreshold_5frule_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_rules_2fthreshold_5frule_2eproto::offsets,
    file_level_enum_descriptors_rules_2fthreshold_5frule_2eproto,
    file_level_service_descriptors_rules_2fthreshold_5frule_2eproto,
};
namespace rules {
// ===================================================================

class ThresholdRule::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ThresholdRule>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ThresholdRule, _impl_._has_bits_);
};

ThresholdRule::ThresholdRule(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ThresholdRule_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rules.ThresholdRule)
}
PROTOBUF_NDEBUG_INLINE ThresholdRule::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rules::ThresholdRule& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        expression_(arena, from.expression_) {}

ThresholdRule::ThresholdRule(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ThresholdRule& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ThresholdRule_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ThresholdRule* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rules.ThresholdRule)
}
PROTOBUF_NDEBUG_INLINE ThresholdRule::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        expression_(arena) {}

inline void ThresholdRule::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ThresholdRule::~ThresholdRule() {
  // @@protoc_insertion_point(destructor:rules.ThresholdRule)
  SharedDtor(*this);
}
inline void ThresholdRule::SharedDtor(MessageLite& self) {
  ThresholdRule& this_ = static_cast<ThresholdRule&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.expression_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ThresholdRule::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ThresholdRule(arena);
}
constexpr auto ThresholdRule::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ThresholdRule),
                                            alignof(ThresholdRule));
}
constexpr auto ThresholdRule::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ThresholdRule_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ThresholdRule::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ThresholdRule>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ThresholdRule::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ThresholdRule>(), &ThresholdRule::ByteSizeLong,
              &ThresholdRule::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ThresholdRule, _impl_._cached_size_),
          false,
      },
      &ThresholdRule::kDescriptorMethods,
      &descriptor_table_rules_2fthreshold_5frule_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ThresholdRule_class_data_ =
        ThresholdRule::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ThresholdRule::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ThresholdRule_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ThresholdRule_class_data_.tc_table);
  return ThresholdRule_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2>
ThresholdRule::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ThresholdRule, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ThresholdRule_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rules::ThresholdRule>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string expression = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ThresholdRule, _impl_.expression_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string expression = 1;
    {PROTOBUF_FIELD_OFFSET(ThresholdRule, _impl_.expression_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\12\0\0\0\0\0\0"
    "rules.ThresholdRule"
    "expression"
  }},
};
PROTOBUF_NOINLINE void ThresholdRule::Clear() {
// @@protoc_insertion_point(message_clear_start:rules.ThresholdRule)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.expression_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ThresholdRule::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ThresholdRule& this_ = static_cast<const ThresholdRule&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ThresholdRule::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ThresholdRule& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rules.ThresholdRule)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string expression = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_expression().empty()) {
      const ::std::string& _s = this_._internal_expression();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rules.ThresholdRule.expression");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rules.ThresholdRule)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ThresholdRule::ByteSizeLong(const MessageLite& base) {
  const ThresholdRule& this_ = static_cast<const ThresholdRule&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ThresholdRule::ByteSizeLong() const {
  const ThresholdRule& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rules.ThresholdRule)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string expression = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_expression().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_expression());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ThresholdRule::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ThresholdRule*>(&to_msg);
  auto& from = static_cast<const ThresholdRule&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:rules.ThresholdRule)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (!from._internal_expression().empty()) {
      _this->_internal_set_expression(from._internal_expression());
    } else {
      if (_this->_impl_.expression_.IsDefault()) {
        _this->_internal_set_expression("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ThresholdRule::CopyFrom(const ThresholdRule& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rules.ThresholdRule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ThresholdRule::InternalSwap(ThresholdRule* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.expression_, &other->_impl_.expression_, arena);
}

::google::protobuf::Metadata ThresholdRule::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rules
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rules_2fthreshold_5frule_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
