// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rules/threshold_rule.proto
// Protobuf C++ Version: 5.27.0

#include "rules/threshold_rule.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rules {

inline constexpr ThresholdRule::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : expression_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ThresholdRule::ThresholdRule(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ThresholdRuleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ThresholdRuleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ThresholdRuleDefaultTypeInternal() {}
  union {
    ThresholdRule _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ThresholdRuleDefaultTypeInternal _ThresholdRule_default_instance_;
}  // namespace rules
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_rules_2fthreshold_5frule_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rules_2fthreshold_5frule_2eproto = nullptr;
const ::uint32_t
    TableStruct_rules_2fthreshold_5frule_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::rules::ThresholdRule, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rules::ThresholdRule, _impl_.expression_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::rules::ThresholdRule)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::rules::_ThresholdRule_default_instance_._instance,
};
const char descriptor_table_protodef_rules_2fthreshold_5frule_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032rules/threshold_rule.proto\022\005rules\"#\n\rT"
    "hresholdRule\022\022\n\nexpression\030\001 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_rules_2fthreshold_5frule_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rules_2fthreshold_5frule_2eproto = {
    false,
    false,
    80,
    descriptor_table_protodef_rules_2fthreshold_5frule_2eproto,
    "rules/threshold_rule.proto",
    &descriptor_table_rules_2fthreshold_5frule_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_rules_2fthreshold_5frule_2eproto::offsets,
    file_level_enum_descriptors_rules_2fthreshold_5frule_2eproto,
    file_level_service_descriptors_rules_2fthreshold_5frule_2eproto,
};
namespace rules {
// ===================================================================

class ThresholdRule::_Internal {
 public:
};

ThresholdRule::ThresholdRule(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rules.ThresholdRule)
}
inline PROTOBUF_NDEBUG_INLINE ThresholdRule::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rules::ThresholdRule& from_msg)
      : expression_(arena, from.expression_),
        _cached_size_{0} {}

ThresholdRule::ThresholdRule(
    ::google::protobuf::Arena* arena,
    const ThresholdRule& from)
    : ::google::protobuf::Message(arena) {
  ThresholdRule* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rules.ThresholdRule)
}
inline PROTOBUF_NDEBUG_INLINE ThresholdRule::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : expression_(arena),
        _cached_size_{0} {}

inline void ThresholdRule::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ThresholdRule::~ThresholdRule() {
  // @@protoc_insertion_point(destructor:rules.ThresholdRule)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ThresholdRule::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.expression_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ThresholdRule::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ThresholdRule, _impl_._cached_size_),
              false,
          },
          &ThresholdRule::MergeImpl,
          &ThresholdRule::kDescriptorMethods,
          &descriptor_table_rules_2fthreshold_5frule_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2> ThresholdRule::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ThresholdRule_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rules::ThresholdRule>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string expression = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ThresholdRule, _impl_.expression_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string expression = 1;
    {PROTOBUF_FIELD_OFFSET(ThresholdRule, _impl_.expression_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\12\0\0\0\0\0\0"
    "rules.ThresholdRule"
    "expression"
  }},
};

PROTOBUF_NOINLINE void ThresholdRule::Clear() {
// @@protoc_insertion_point(message_clear_start:rules.ThresholdRule)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.expression_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ThresholdRule::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rules.ThresholdRule)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string expression = 1;
  if (!this->_internal_expression().empty()) {
    const std::string& _s = this->_internal_expression();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rules.ThresholdRule.expression");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rules.ThresholdRule)
  return target;
}

::size_t ThresholdRule::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rules.ThresholdRule)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string expression = 1;
  if (!this->_internal_expression().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_expression());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ThresholdRule::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ThresholdRule*>(&to_msg);
  auto& from = static_cast<const ThresholdRule&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rules.ThresholdRule)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_expression().empty()) {
    _this->_internal_set_expression(from._internal_expression());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ThresholdRule::CopyFrom(const ThresholdRule& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rules.ThresholdRule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ThresholdRule::InternalSwap(ThresholdRule* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.expression_, &other->_impl_.expression_, arena);
}

::google::protobuf::Metadata ThresholdRule::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rules
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rules_2fthreshold_5frule_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
