// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rules/threshold_rule.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_rules_2fthreshold_5frule_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_rules_2fthreshold_5frule_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rules_2fthreshold_5frule_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rules_2fthreshold_5frule_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_rules_2fthreshold_5frule_2eproto;
namespace rules {
class ThresholdRule;
struct ThresholdRuleDefaultTypeInternal;
extern ThresholdRuleDefaultTypeInternal _ThresholdRule_default_instance_;
}  // namespace rules
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace rules {

// ===================================================================


// -------------------------------------------------------------------

class ThresholdRule final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rules.ThresholdRule) */ {
 public:
  inline ThresholdRule() : ThresholdRule(nullptr) {}
  ~ThresholdRule() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ThresholdRule(
      ::google::protobuf::internal::ConstantInitialized);

  inline ThresholdRule(const ThresholdRule& from) : ThresholdRule(nullptr, from) {}
  inline ThresholdRule(ThresholdRule&& from) noexcept
      : ThresholdRule(nullptr, std::move(from)) {}
  inline ThresholdRule& operator=(const ThresholdRule& from) {
    CopyFrom(from);
    return *this;
  }
  inline ThresholdRule& operator=(ThresholdRule&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ThresholdRule& default_instance() {
    return *internal_default_instance();
  }
  static inline const ThresholdRule* internal_default_instance() {
    return reinterpret_cast<const ThresholdRule*>(
        &_ThresholdRule_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ThresholdRule& a, ThresholdRule& b) { a.Swap(&b); }
  inline void Swap(ThresholdRule* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ThresholdRule* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ThresholdRule* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ThresholdRule>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ThresholdRule& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ThresholdRule& from) { ThresholdRule::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ThresholdRule* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "rules.ThresholdRule"; }

 protected:
  explicit ThresholdRule(::google::protobuf::Arena* arena);
  ThresholdRule(::google::protobuf::Arena* arena, const ThresholdRule& from);
  ThresholdRule(::google::protobuf::Arena* arena, ThresholdRule&& from) noexcept
      : ThresholdRule(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExpressionFieldNumber = 1,
  };
  // string expression = 1;
  void clear_expression() ;
  const std::string& expression() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_expression(Arg_&& arg, Args_... args);
  std::string* mutable_expression();
  PROTOBUF_NODISCARD std::string* release_expression();
  void set_allocated_expression(std::string* value);

  private:
  const std::string& _internal_expression() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_expression(
      const std::string& value);
  std::string* _internal_mutable_expression();

  public:
  // @@protoc_insertion_point(class_scope:rules.ThresholdRule)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      38, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ThresholdRule_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ThresholdRule& from_msg);
    ::google::protobuf::internal::ArenaStringPtr expression_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rules_2fthreshold_5frule_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ThresholdRule

// string expression = 1;
inline void ThresholdRule::clear_expression() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expression_.ClearToEmpty();
}
inline const std::string& ThresholdRule::expression() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rules.ThresholdRule.expression)
  return _internal_expression();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ThresholdRule::set_expression(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expression_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rules.ThresholdRule.expression)
}
inline std::string* ThresholdRule::mutable_expression() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_expression();
  // @@protoc_insertion_point(field_mutable:rules.ThresholdRule.expression)
  return _s;
}
inline const std::string& ThresholdRule::_internal_expression() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.expression_.Get();
}
inline void ThresholdRule::_internal_set_expression(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expression_.Set(value, GetArena());
}
inline std::string* ThresholdRule::_internal_mutable_expression() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.expression_.Mutable( GetArena());
}
inline std::string* ThresholdRule::release_expression() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rules.ThresholdRule.expression)
  return _impl_.expression_.Release();
}
inline void ThresholdRule::set_allocated_expression(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expression_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.expression_.IsDefault()) {
          _impl_.expression_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rules.ThresholdRule.expression)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace rules


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_rules_2fthreshold_5frule_2eproto_2epb_2eh
