# Generated by Django 5.2.7 on 2025-10-26 00:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MLRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_uuid', models.CharField(default='', max_length=255)),
                ('lower_bound', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PatternRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_delta_time', models.IntegerField()),
                ('max_count', models.IntegerField()),
                ('expression', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('ML', 'ML'), ('THRESHOLD', 'THRESHOLD'), ('COMPOSITE', 'COMPOSITE'), ('PATTERN', 'PATTERN')], max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='myapp.profile')),
            ],
        ),
    ]
