# Generated by Django 5.2.7 on 2025-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_uuid', models.UUIDField()),
                ('profile_name', models.CharField(max_length=255)),
                ('config_uuid', models.UUIDField()),
                ('config_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ERROR', 'Error'), ('NOT_FRAUD', 'Not Fraud'), ('FRAUD', 'Fraud')], max_length=20)),
                ('transaction_id', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rule_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
